-- TRES ENCANTOS
-- Fase 1: modelo auditable de pagos + RPCs atomicos para ventas y apartados.
--
-- Esta migracion es ADITIVA:
--   * conserva record_sale_atomic v1;
--   * conserva temporalmente las policies INSERT/UPDATE/DELETE actuales de sales;
--   * permite desplegar primero la base y despues el frontend sin romper clientes cacheados.
--
-- Ejecutar completa en Supabase SQL Editor. Al terminar, desplegar el frontend v2.

BEGIN;

-- Si la migracion se vuelve a ejecutar y los triggers de compatibilidad ya
-- existen, evita que el propio backfill se interprete como una operacion POS.
SELECT set_config('tresencantos.rpc_v2', 'on', true);

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -----------------------------------------------------------------------------
-- 1. Estado explicito y marcas temporales en sales
-- -----------------------------------------------------------------------------

ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS origin_type text;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS liquidated_at timestamptz;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS last_payment_at timestamptz;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS updated_at timestamptz;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS version bigint;

-- origin_type nunca cambia. type se mantiene por compatibilidad:
--   apartado activo -> type='apartado'
--   venta directa o apartado liquidado -> type='venta'
UPDATE public.sales
SET origin_type = CASE
  WHEN type = 'apartado' THEN 'apartado'
  WHEN jsonb_typeof(abonos) = 'array' AND jsonb_array_length(abonos) > 0 THEN 'apartado'
  ELSE 'venta'
END
WHERE origin_type IS NULL;

UPDATE public.sales
SET status = CASE
  WHEN cancelled_at IS NOT NULL THEN 'cancelado'
  WHEN origin_type = 'apartado'
       AND COALESCE(paid_amount, 0) < COALESCE(total, 0) THEN 'activo'
  ELSE 'liquidado'
END
WHERE status IS NULL;

UPDATE public.sales SET version = 0 WHERE version IS NULL;
UPDATE public.sales
SET updated_at = COALESCE(cancelled_at, created_at, now())
WHERE updated_at IS NULL;

ALTER TABLE public.sales ALTER COLUMN origin_type SET DEFAULT 'venta';
ALTER TABLE public.sales ALTER COLUMN origin_type SET NOT NULL;
ALTER TABLE public.sales ALTER COLUMN status SET DEFAULT 'liquidado';
ALTER TABLE public.sales ALTER COLUMN status SET NOT NULL;
ALTER TABLE public.sales ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE public.sales ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE public.sales ALTER COLUMN version SET DEFAULT 0;
ALTER TABLE public.sales ALTER COLUMN version SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.sales'::regclass
      AND conname = 'sales_origin_type_check'
  ) THEN
    ALTER TABLE public.sales
      ADD CONSTRAINT sales_origin_type_check
      CHECK (origin_type IN ('venta', 'apartado')) NOT VALID;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.sales'::regclass
      AND conname = 'sales_status_check'
  ) THEN
    ALTER TABLE public.sales
      ADD CONSTRAINT sales_status_check
      CHECK (status IN ('activo', 'liquidado', 'cancelado')) NOT VALID;
  END IF;
END;
$$;

ALTER TABLE public.sales VALIDATE CONSTRAINT sales_origin_type_check;
ALTER TABLE public.sales VALIDATE CONSTRAINT sales_status_check;

CREATE INDEX IF NOT EXISTS sales_status_idx
  ON public.sales (status, created_at DESC);
CREATE INDEX IF NOT EXISTS sales_last_payment_at_idx
  ON public.sales (last_payment_at DESC)
  WHERE last_payment_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS sales_active_apartados_idx
  ON public.sales (id)
  WHERE origin_type = 'apartado' AND status = 'activo' AND cancelled_at IS NULL;

-- -----------------------------------------------------------------------------
-- 2. Ledger inmutable de dinero recibido/devuelto
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.sale_payments (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id            bigint NOT NULL REFERENCES public.sales(id) ON DELETE RESTRICT,
  request_id         uuid,
  request_line       smallint NOT NULL DEFAULT 1,
  legacy_key         text,
  kind               text NOT NULL,
  amount             numeric NOT NULL,
  method             text NOT NULL DEFAULT 'unknown',
  paid_at            timestamptz,
  recorded_at        timestamptz NOT NULL DEFAULT now(),
  collected_by       uuid,
  collected_by_email text,
  is_estimated       boolean NOT NULL DEFAULT false,
  source             text NOT NULL DEFAULT 'rpc',
  meta               jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT sale_payments_kind_check
    CHECK (kind IN ('payment', 'refund', 'adjustment')),
  CONSTRAINT sale_payments_amount_check
    CHECK (
      (kind = 'payment' AND amount > 0)
      OR (kind = 'refund' AND amount < 0)
      OR (kind = 'adjustment' AND amount <> 0)
    ),
  CONSTRAINT sale_payments_method_check
    CHECK (method IN ('efectivo', 'transferencia', 'unknown'))
);

ALTER TABLE public.sale_payments ADD COLUMN IF NOT EXISTS request_line smallint NOT NULL DEFAULT 1;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.sale_payments'::regclass
      AND conname = 'sale_payments_amount_finite_check'
  ) THEN
    ALTER TABLE public.sale_payments
      ADD CONSTRAINT sale_payments_amount_finite_check
      CHECK (amount::text NOT IN ('NaN', 'Infinity', '-Infinity')) NOT VALID;
  END IF;
END;
$$;
ALTER TABLE public.sale_payments VALIDATE CONSTRAINT sale_payments_amount_finite_check;

-- Una cancelacion/devolucion puede producir una linea por metodo original.
DROP INDEX IF EXISTS public.sale_payments_request_id_uidx;
CREATE UNIQUE INDEX sale_payments_request_id_uidx
  ON public.sale_payments (request_id, request_line)
  WHERE request_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS sale_payments_legacy_key_uidx
  ON public.sale_payments (legacy_key)
  WHERE legacy_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS sale_payments_paid_at_idx
  ON public.sale_payments (paid_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS sale_payments_sale_id_idx
  ON public.sale_payments (sale_id, id);

ALTER TABLE public.sale_payments ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'sale_payments'
      AND policyname = 'sale_payments_auth_select'
  ) THEN
    CREATE POLICY sale_payments_auth_select ON public.sale_payments
      FOR SELECT TO authenticated
      USING (auth.role() = 'authenticated');
  END IF;
END;
$$;

REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.sale_payments FROM anon, authenticated;
GRANT SELECT ON public.sale_payments TO authenticated;

-- Tabla privada de idempotencia. Ningun cliente la consulta directamente.
CREATE TABLE IF NOT EXISTS public.pos_rpc_requests (
  request_id  uuid PRIMARY KEY,
  operation   text NOT NULL,
  actor_id    uuid NOT NULL,
  actor_email text,
  sale_id     bigint REFERENCES public.sales(id) ON DELETE SET NULL,
  response    jsonb NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS pos_rpc_requests_created_at_idx
  ON public.pos_rpc_requests (created_at DESC);

ALTER TABLE public.pos_rpc_requests ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.pos_rpc_requests FROM PUBLIC, anon, authenticated;

-- -----------------------------------------------------------------------------
-- 3. Helpers privados
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.te_try_numeric(p_value text)
RETURNS numeric
LANGUAGE plpgsql
IMMUTABLE
SET search_path = pg_catalog, public
AS $$
BEGIN
  RETURN p_value::numeric;
EXCEPTION WHEN OTHERS THEN
  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.te_try_timestamptz(p_value text)
RETURNS timestamptz
LANGUAGE plpgsql
STABLE
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF p_value IS NULL OR btrim(p_value) = '' THEN
    RETURN NULL;
  END IF;
  RETURN p_value::timestamptz;
EXCEPTION WHEN OTHERS THEN
  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.te_try_jsonb(p_value text)
RETURNS jsonb
LANGUAGE plpgsql
IMMUTABLE
SET search_path = pg_catalog
AS $$
BEGIN
  RETURN p_value::jsonb;
EXCEPTION WHEN OTHERS THEN
  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.te_require_positive_bigint(
  p_value text,
  p_label text DEFAULT 'valor'
)
RETURNS bigint
LANGUAGE plpgsql
IMMUTABLE
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_value numeric := public.te_try_numeric(p_value);
BEGIN
  IF v_value IS NULL OR v_value <= 0 OR v_value <> trunc(v_value)
     OR v_value > 9223372036854775807::numeric THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = format('%s debe ser un entero positivo valido', COALESCE(p_label, 'valor'));
  END IF;
  RETURN v_value::bigint;
END;
$$;

CREATE OR REPLACE FUNCTION public.te_numeric_is_finite(p_value numeric)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
SET search_path = pg_catalog
AS $$
  SELECT p_value IS NOT NULL
     AND p_value::text NOT IN ('NaN', 'Infinity', '-Infinity');
$$;

-- Migra roles confiables a app_metadata. Nunca copia raw_user_meta_data: ese
-- campo puede modificarlo el propio usuario. config.user_permissions sigue
-- siendo la fuente administrable y tiene prioridad cuando contiene un rol
-- valido.
WITH permission_config AS (
  SELECT COALESCE(public.te_try_jsonb(value::text), '{}'::jsonb) AS value
  FROM public.config
  WHERE id = 'user_permissions'
), desired_roles AS (
  SELECT
    u.id,
    COALESCE(
      (SELECT pc.value -> lower(u.email) ->> 'role' FROM permission_config pc),
      u.raw_app_meta_data ->> 'role',
      'operador'
    ) AS role
  FROM auth.users u
)
UPDATE auth.users u
SET raw_app_meta_data = COALESCE(u.raw_app_meta_data, '{}'::jsonb)
                        || jsonb_build_object('role', d.role)
FROM desired_roles d
WHERE d.id = u.id
  AND d.role IN ('superadmin', 'encargado', 'duena', 'operador');

-- Falla de forma segura antes de reemplazar las policies si el proyecto aun
-- conserva roles solo en user_metadata. En ese caso se debe sembrar al menos
-- un superadmin en config.user_permissions o raw_app_meta_data y reintentar.
DO $$
DECLARE
  v_config     jsonb := '{}'::jsonb;
  v_has_config boolean := false;
  v_has_admin  boolean := false;
BEGIN
  SELECT public.te_try_jsonb(c.value::text), true
    INTO v_config, v_has_config
  FROM public.config c
  WHERE c.id = 'user_permissions'
    AND public.te_try_jsonb(c.value::text) IS NOT NULL;

  IF v_has_config THEN
    SELECT EXISTS (
      SELECT 1
      FROM auth.users u
      WHERE v_config -> lower(u.email) ->> 'role' = 'superadmin'
    ) INTO v_has_admin;
  ELSE
    SELECT EXISTS (
      SELECT 1
      FROM auth.users u
      WHERE u.raw_app_meta_data ->> 'role' = 'superadmin'
    ) INTO v_has_admin;
  END IF;

  IF NOT v_has_admin THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = 'No hay un superadmin confiable en config.user_permissions ni app_metadata',
      HINT = 'Asigna role=superadmin en config.user_permissions o auth.users.raw_app_meta_data antes de ejecutar la migracion.';
  END IF;
END;
$$;

-- Reemplaza el helper RLS inseguro. Consulta auth.users y el config vigente en
-- servidor, por lo que ascensos/demisiones aplican sin esperar un JWT nuevo.
CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS text
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_uid         uuid := auth.uid();
  v_email       text;
  v_app_role    text;
  v_config      jsonb := '{}'::jsonb;
  v_config_role text;
  v_has_config  boolean := false;
BEGIN
  IF v_uid IS NULL THEN
    RETURN 'anon';
  END IF;

  SELECT lower(u.email), u.raw_app_meta_data ->> 'role'
    INTO v_email, v_app_role
  FROM auth.users u
  WHERE u.id = v_uid;

  BEGIN
    SELECT value::jsonb, true INTO v_config, v_has_config
    FROM public.config
    WHERE id = 'user_permissions';
  EXCEPTION WHEN OTHERS THEN
    v_config := '{}'::jsonb;
    v_has_config := false;
  END;

  v_config_role := v_config -> v_email ->> 'role';
  IF v_config_role IN ('superadmin', 'encargado', 'duena', 'operador') THEN
    RETURN v_config_role;
  END IF;
  -- Si existe el mapa administrable, omitir/remover un usuario equivale a
  -- degradarlo a operador; no conserva para siempre el rol del rollout.
  IF v_has_config THEN
    RETURN 'operador';
  END IF;
  IF v_app_role IN ('superadmin', 'encargado', 'duena', 'operador') THEN
    RETURN v_app_role;
  END IF;
  RETURN 'operador';
END;
$$;

REVOKE ALL ON FUNCTION public.get_user_role() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_user_role() TO anon, authenticated;

-- Lee los overrides de config.id='user_permissions' y, si no existen,
-- aplica exactamente los defaults usados por shared.js.
CREATE OR REPLACE FUNCTION public.te_has_permission(p_permission text)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_email       text;
  -- app_metadata no puede modificarla el usuario. user_metadata si puede ser
  -- modificada por el propio usuario y nunca debe autorizar SECURITY DEFINER.
  v_role        text := public.get_user_role();
  v_permissions jsonb;
  v_user        jsonb;
  v_override    jsonb;
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN false;
  END IF;

  SELECT lower(u.email) INTO v_email
  FROM auth.users u
  WHERE u.id = auth.uid();

  BEGIN
    SELECT value::jsonb
      INTO v_permissions
    FROM public.config
    WHERE id = 'user_permissions';
  EXCEPTION WHEN OTHERS THEN
    v_permissions := '{}'::jsonb;
  END;

  v_user := COALESCE(v_permissions -> v_email, '{}'::jsonb);
  IF jsonb_typeof(v_user -> 'role') = 'string'
     AND (v_user ->> 'role') IN ('superadmin', 'encargado', 'duena', 'operador') THEN
    v_role := v_user ->> 'role';
  END IF;

  v_override := v_user -> p_permission;
  IF jsonb_typeof(v_override) = 'boolean' THEN
    RETURN (v_override #>> '{}')::boolean;
  END IF;

  RETURN CASE v_role
    WHEN 'superadmin' THEN p_permission IN (
      'canAddProduct', 'canEditProduct', 'canDeleteProduct', 'canPublishProduct',
      'canBulkDelete', 'canImportJSON', 'canMasivo', 'canCancelSale',
      'canEditApartado', 'canViewReports', 'canViewActivity', 'canManageSettings'
    )
    WHEN 'encargado' THEN p_permission IN (
      'canAddProduct', 'canEditProduct', 'canDeleteProduct', 'canPublishProduct',
      'canBulkDelete', 'canCancelSale'
    )
    WHEN 'duena' THEN p_permission IN (
      'canAddProduct', 'canEditProduct', 'canDeleteProduct', 'canPublishProduct',
      'canEditApartado', 'canViewReports', 'canViewActivity'
    )
    WHEN 'operador' THEN p_permission IN ('canAddProduct', 'canEditProduct')
    ELSE false
  END;
END;
$$;

-- Fuente autoritativa para construir la UI del usuario actual. No expone el
-- mapa completo de config ni confia en user_metadata/cache del navegador.
CREATE OR REPLACE FUNCTION public.get_my_permissions()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_role text;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'No autenticado';
  END IF;

  v_role := public.get_user_role();
  RETURN jsonb_build_object(
    'role', v_role,
    'canAddProduct', public.te_has_permission('canAddProduct'),
    'canEditProduct', public.te_has_permission('canEditProduct'),
    'canDeleteProduct', public.te_has_permission('canDeleteProduct'),
    'canPublishProduct', public.te_has_permission('canPublishProduct'),
    'canBulkDelete', public.te_has_permission('canBulkDelete'),
    'canImportJSON', public.te_has_permission('canImportJSON'),
    'canMasivo', public.te_has_permission('canMasivo'),
    'canCancelSale', public.te_has_permission('canCancelSale'),
    'canEditApartado', public.te_has_permission('canEditApartado'),
    'canViewReports', public.te_has_permission('canViewReports'),
    'canViewActivity', public.te_has_permission('canViewActivity'),
    'canManageSettings', public.te_has_permission('canManageSettings')
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.te_rpc_replay(
  p_request_id uuid,
  p_operation text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_row public.pos_rpc_requests%ROWTYPE;
BEGIN
  IF p_request_id IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'request_id es obligatorio';
  END IF;
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'No autenticado';
  END IF;

  -- Serializa dos reintentos simultaneos del mismo request_id.
  PERFORM pg_advisory_xact_lock(hashtextextended(p_request_id::text, 0));

  SELECT * INTO v_row
  FROM public.pos_rpc_requests
  WHERE request_id = p_request_id;

  IF NOT FOUND THEN
    RETURN NULL;
  END IF;
  IF v_row.actor_id <> auth.uid() OR v_row.operation <> p_operation THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = 'request_id ya fue usado para otra operacion o usuario';
  END IF;
  RETURN v_row.response;
END;
$$;

CREATE OR REPLACE FUNCTION public.te_rpc_store(
  p_request_id uuid,
  p_operation text,
  p_sale_id bigint,
  p_response jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  INSERT INTO public.pos_rpc_requests (
    request_id, operation, actor_id, actor_email, sale_id, response
  ) VALUES (
    p_request_id,
    p_operation,
    auth.uid(),
    lower(auth.jwt() ->> 'email'),
    p_sale_id,
    p_response
  );
END;
$$;

-- Permite resolver un resultado ambiguo despues de recargar (por ejemplo, si
-- la red se corto justo despues del COMMIT). Nunca revela requests de otro
-- usuario y toma el mismo lock que las RPC de escritura.
CREATE OR REPLACE FUNCTION public.get_pos_rpc_result(p_request_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_response jsonb;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'No autenticado';
  END IF;
  IF p_request_id IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'request_id es obligatorio';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended(p_request_id::text, 0));

  SELECT r.response INTO v_response
  FROM public.pos_rpc_requests r
  WHERE r.request_id = p_request_id
    AND r.actor_id = auth.uid();

  IF NOT FOUND THEN
    RETURN jsonb_build_object('found', false);
  END IF;
  RETURN jsonb_build_object('found', true, 'response', v_response);
END;
$$;

-- Normaliza items y toma el snapshot del kit DESDE products. Nunca confia en
-- kit_items enviados por el navegador.
CREATE OR REPLACE FUNCTION public.te_snapshot_sale_items(p_items jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_item              jsonb;
  v_component         jsonb;
  v_product           public.products%ROWTYPE;
  v_raw_id            numeric;
  v_raw_qty           numeric;
  v_raw_price         numeric;
  v_raw_component_id  numeric;
  v_raw_component_qty numeric;
  v_id                bigint;
  v_qty               integer;
  v_component_id      bigint;
  v_component_qty     integer;
  v_price             numeric;
  v_name              text;
  v_kit_snapshot      jsonb;
  v_snapshot          jsonb := '[]'::jsonb;
  v_normalized        jsonb;
BEGIN
  IF jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'La venta debe tener al menos un producto';
  END IF;

  FOR v_item IN SELECT value FROM jsonb_array_elements(p_items)
  LOOP
    v_raw_id := public.te_try_numeric(v_item ->> 'id');
    v_raw_qty := public.te_try_numeric(v_item ->> 'qty');
    v_raw_price := public.te_try_numeric(v_item ->> 'price');

    IF v_raw_id IS NULL OR v_raw_id <= 0 OR v_raw_id <> trunc(v_raw_id)
       OR v_raw_id > 9223372036854775807::numeric THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Producto sin id valido';
    END IF;
    v_id := v_raw_id::bigint;

    IF v_raw_qty IS NULL OR v_raw_qty <= 0 OR v_raw_qty <> trunc(v_raw_qty)
       OR v_raw_qty > 2147483647::numeric THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = format('Cantidad invalida para producto id=%s', v_id);
    END IF;
    v_qty := v_raw_qty::integer;

    v_price := round(v_raw_price, 2);
    IF NOT public.te_numeric_is_finite(v_price) OR v_price < 0 THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = format('Precio invalido para producto id=%s', v_id);
    END IF;

    SELECT * INTO v_product
    FROM public.products
    WHERE id = v_id;
    IF NOT FOUND THEN
      RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = format('Producto id=%s no existe', v_id);
    END IF;

    v_name := COALESCE(NULLIF(btrim(v_item ->> 'name'), ''), v_product.name);
    v_normalized := jsonb_build_object(
      'id', v_id,
      'name', v_name,
      'price', v_price,
      'qty', v_qty,
      'subtotal', round(v_price * v_qty, 2)
    );

    -- Valida y normaliza el kit que vive en base. Asi el snapshot nunca puede
    -- redondear un id/cantidad fraccional hacia otro producto por un cast.
    v_kit_snapshot := '[]'::jsonb;
    IF jsonb_typeof(v_product.kit_items) = 'array' THEN
      FOR v_component IN SELECT value FROM jsonb_array_elements(v_product.kit_items)
      LOOP
        v_raw_component_id := public.te_try_numeric(v_component ->> 'id');
        v_raw_component_qty := COALESCE(public.te_try_numeric(v_component ->> 'qty'), 1);

        IF v_raw_component_id IS NULL OR v_raw_component_id <= 0
           OR v_raw_component_id <> trunc(v_raw_component_id)
           OR v_raw_component_id > 9223372036854775807::numeric THEN
          RAISE EXCEPTION USING
            ERRCODE = '22023',
            MESSAGE = format('Kit id=%s contiene un componente sin id valido', v_id);
        END IF;
        IF v_raw_component_qty <= 0 OR v_raw_component_qty <> trunc(v_raw_component_qty)
           OR v_raw_component_qty > 2147483647::numeric THEN
          RAISE EXCEPTION USING
            ERRCODE = '22023',
            MESSAGE = format('Kit id=%s contiene una cantidad invalida', v_id);
        END IF;

        v_component_id := v_raw_component_id::bigint;
        v_component_qty := v_raw_component_qty::integer;
        v_kit_snapshot := v_kit_snapshot || jsonb_build_array(jsonb_build_object(
          'id', v_component_id,
          'name', NULLIF(btrim(v_component ->> 'name'), ''),
          'qty', v_component_qty
        ));
      END LOOP;
    END IF;

    -- Tambien se guarda [] para un producto regular. La presencia de la llave
    -- hace el snapshot autoritativo si ese producto se convierte en kit luego.
    v_normalized := v_normalized || jsonb_build_object(
      'kit_items', v_kit_snapshot,
      'kit_snapshot_estimated', false
    );

    v_snapshot := v_snapshot || jsonb_build_array(v_normalized);
  END LOOP;

  RETURN v_snapshot;
END;
$$;

-- Fusiona un snapshot nuevo (siempre construido en servidor) con los kits ya
-- congelados de la venta. Los productos nuevos conservan el kit actual; los
-- existentes nunca cambian de componentes por una edicion no relacionada.
CREATE OR REPLACE FUNCTION public.te_preserve_item_kit_snapshots(
  p_new_items jsonb,
  p_old_items jsonb
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT COALESCE(jsonb_agg(
    CASE
      WHEN old_item.item IS NOT NULL
           AND jsonb_typeof(old_item.item -> 'kit_items') = 'array'
        THEN n.item || jsonb_build_object(
          'kit_items', old_item.item -> 'kit_items',
          'kit_snapshot_estimated', COALESCE(
            old_item.item -> 'kit_snapshot_estimated', 'true'::jsonb
          )
        )
      ELSE n.item
    END
    ORDER BY n.ord
  ), '[]'::jsonb)
  FROM jsonb_array_elements(
    CASE WHEN jsonb_typeof(p_new_items) = 'array' THEN p_new_items ELSE '[]'::jsonb END
  ) WITH ORDINALITY AS n(item, ord)
  LEFT JOIN LATERAL (
    SELECT o.item
    FROM jsonb_array_elements(
      CASE WHEN jsonb_typeof(p_old_items) = 'array' THEN p_old_items ELSE '[]'::jsonb END
    ) AS o(item)
    WHERE public.te_try_numeric(o.item ->> 'id') = public.te_try_numeric(n.item ->> 'id')
    LIMIT 1
  ) old_item ON true;
$$;

-- Expande items de venta a demanda real de inventario. Usa primero el snapshot
-- guardado; para filas historicas sin snapshot usa el kit actual como fallback.
CREATE OR REPLACE FUNCTION public.te_inventory_demand(p_items jsonb)
RETURNS TABLE(product_id bigint, required_qty bigint)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  WITH item_rows AS (
    SELECT
      item,
      public.te_require_positive_bigint(item ->> 'id', 'id de producto') AS item_id,
      public.te_require_positive_bigint(COALESCE(item ->> 'qty', '1'), 'cantidad de producto') AS item_qty
    FROM jsonb_array_elements(
      CASE WHEN jsonb_typeof(p_items) = 'array' THEN p_items ELSE '[]'::jsonb END
    ) AS x(item)
  ), item_sources AS (
    SELECT
      i.*,
      CASE
        -- Cualquier array presente, incluso [], es un snapshot autoritativo.
        WHEN jsonb_typeof(i.item -> 'kit_items') = 'array'
          THEN i.item -> 'kit_items'
        WHEN jsonb_typeof(p.kit_items) = 'array'
             AND jsonb_array_length(p.kit_items) > 0
          THEN p.kit_items
        ELSE '[]'::jsonb
      END AS kit_items
    FROM item_rows i
    LEFT JOIN public.products p ON p.id = i.item_id
  ), expanded AS (
    SELECT
      public.te_require_positive_bigint(component ->> 'id', 'id de componente') AS product_id,
      s.item_qty * public.te_require_positive_bigint(
        COALESCE(component ->> 'qty', '1'), 'cantidad de componente'
      ) AS required_qty
    FROM item_sources s
    CROSS JOIN LATERAL jsonb_array_elements(s.kit_items) AS k(component)
    WHERE jsonb_array_length(s.kit_items) > 0

    UNION ALL

    SELECT s.item_id, s.item_qty
    FROM item_sources s
    WHERE jsonb_array_length(s.kit_items) = 0
  )
  SELECT e.product_id, SUM(e.required_qty)::bigint
  FROM expanded e
  GROUP BY e.product_id
  ORDER BY e.product_id;
$$;

CREATE OR REPLACE FUNCTION public.te_assert_authoritative_inventory_snapshot(
  p_items jsonb,
  p_operation text
)
RETURNS void
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM jsonb_array_elements(
      CASE WHEN jsonb_typeof(p_items) = 'array' THEN p_items ELSE '[]'::jsonb END
    ) AS i(item)
    WHERE COALESCE((i.item ->> 'kit_snapshot_estimated')::boolean, false)
      AND jsonb_typeof(i.item -> 'kit_items') = 'array'
      AND jsonb_array_length(i.item -> 'kit_items') > 0
  ) THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = format('No se puede %s: el apartado usa un kit historico cuya composicion es estimada', p_operation),
      HINT = 'Revisa manualmente los componentes y corrige el snapshot antes de mutar inventario.';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.te_refresh_apartado_product_flags(p_product_ids bigint[])
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF COALESCE(array_length(p_product_ids, 1), 0) = 0 THEN
    RETURN;
  END IF;

  WITH reserved AS (
    SELECT d.product_id, SUM(d.required_qty)::bigint AS reserved_qty
    FROM public.sales s
    CROSS JOIN LATERAL public.te_inventory_demand(s.items) d
    WHERE s.origin_type = 'apartado'
      AND s.status = 'activo'
      AND s.cancelled_at IS NULL
      AND d.product_id = ANY(p_product_ids)
    GROUP BY d.product_id
  )
  UPDATE public.products p
  SET
    is_apartado = CASE
      WHEN COALESCE(p.is_archived, false) THEN false
      ELSE (COALESCE(p.stock, 0) <= 0 AND COALESCE(r.reserved_qty, 0) > 0)
    END,
    out_of_stock = CASE
      WHEN COALESCE(p.is_archived, false) THEN true
      WHEN COALESCE(p.stock, 0) <= 0 THEN COALESCE(r.reserved_qty, 0) = 0
      ELSE false
    END,
    -- La disponibilidad se controla con out_of_stock/is_apartado. No destruye
    -- la preferencia editorial is_published al agotarse, para que una
    -- cancelacion pueda restaurar visibilidad sin publicar borradores ocultos.
    is_published = CASE
      WHEN COALESCE(p.is_archived, false) THEN false
      ELSE p.is_published
    END
  FROM (SELECT unnest(p_product_ids) AS product_id) ids
  LEFT JOIN reserved r ON r.product_id = ids.product_id
  WHERE p.id = ids.product_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.te_products_state(p_product_ids bigint[])
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'id', p.id,
        'stock', p.stock,
        'out_of_stock', p.out_of_stock,
        'is_apartado', p.is_apartado,
        'is_published', p.is_published
      ) ORDER BY p.id
    ),
    '[]'::jsonb
  )
  FROM public.products p
  WHERE p.id = ANY(COALESCE(p_product_ids, ARRAY[]::bigint[]));
$$;

CREATE OR REPLACE FUNCTION public.te_log_activity(
  p_action text,
  p_summary text,
  p_meta jsonb DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  INSERT INTO public.activity_log (action, user_email, summary, meta)
  VALUES (
    p_action,
    COALESCE(lower(auth.jwt() ->> 'email'), 'desconocido'),
    p_summary,
    p_meta
  );
END;
$$;

REVOKE ALL ON FUNCTION public.te_try_numeric(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.te_try_timestamptz(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.te_try_jsonb(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.te_require_positive_bigint(text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.te_numeric_is_finite(numeric) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.te_has_permission(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_my_permissions() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.te_rpc_replay(uuid, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.te_rpc_store(uuid, text, bigint, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_pos_rpc_result(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.te_snapshot_sale_items(jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.te_preserve_item_kit_snapshots(jsonb, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.te_inventory_demand(jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.te_assert_authoritative_inventory_snapshot(jsonb, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.te_refresh_apartado_product_flags(bigint[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.te_products_state(bigint[]) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.te_log_activity(text, text, jsonb) FROM PUBLIC;

-- -----------------------------------------------------------------------------
-- 4. Backfill auditable
-- -----------------------------------------------------------------------------

-- Congela la composicion actual de kits en ventas historicas que aun no tenian
-- snapshot. Se marca estimated=true porque no podemos afirmar que el kit nunca
-- cambio desde la venta.
UPDATE public.sales s
SET items = COALESCE((
      SELECT jsonb_agg(
        CASE
          WHEN jsonb_typeof(i.item -> 'kit_items') = 'array'
            THEN i.item
          WHEN jsonb_typeof(p.kit_items) = 'array'
               AND jsonb_array_length(p.kit_items) > 0
            THEN i.item || jsonb_build_object(
              'kit_items', p.kit_items,
              'kit_snapshot_estimated', true
            )
          ELSE i.item || jsonb_build_object(
            'kit_items', '[]'::jsonb,
            'kit_snapshot_estimated', true
          )
        END
        ORDER BY i.ord
      )
      FROM jsonb_array_elements(s.items) WITH ORDINALITY AS i(item, ord)
      LEFT JOIN public.products p
        ON p.id::numeric = public.te_try_numeric(i.item ->> 'id')
       AND public.te_try_numeric(i.item ->> 'id') > 0
       AND public.te_try_numeric(i.item ->> 'id') = trunc(public.te_try_numeric(i.item ->> 'id'))
    ), s.items),
    updated_at = COALESCE(s.updated_at, now())
WHERE jsonb_typeof(s.items) = 'array'
  AND jsonb_array_length(s.items) > 0;

-- Un movimiento por cada abono historico. Los campos desconocidos quedan como
-- unknown/NULL y la fila se marca estimated; nunca se inventa fecha o metodo.
INSERT INTO public.sale_payments (
  sale_id, legacy_key, kind, amount, method, paid_at,
  collected_by, collected_by_email, is_estimated, source, meta
)
SELECT
  s.id,
  format('legacy-abono:%s:%s', s.id, a.ord),
  CASE WHEN parsed.amount < 0 THEN 'refund' ELSE 'payment' END,
  parsed.amount,
  parsed.method,
  parsed.paid_at,
  NULL,
  NULL,
  (parsed.method = 'unknown' OR parsed.paid_at IS NULL),
  'legacy_abono',
  jsonb_build_object(
    'ordinal', a.ord,
    'raw', a.entry,
    'audit_note', CASE
      WHEN parsed.method = 'unknown' OR parsed.paid_at IS NULL
        THEN 'Fecha o metodo historico no disponible'
      ELSE 'Migrado desde sales.abonos'
    END
  )
FROM public.sales s
CROSS JOIN LATERAL jsonb_array_elements(
  CASE WHEN jsonb_typeof(s.abonos) = 'array' THEN s.abonos ELSE '[]'::jsonb END
) WITH ORDINALITY AS a(entry, ord)
CROSS JOIN LATERAL (
  SELECT
    round(public.te_try_numeric(a.entry ->> 'amount'), 2) AS amount,
    CASE lower(a.entry ->> 'method')
      WHEN 'efectivo' THEN 'efectivo'
      WHEN 'transferencia' THEN 'transferencia'
      ELSE 'unknown'
    END AS method,
    public.te_try_timestamptz(a.entry ->> 'date') AS paid_at
) parsed
WHERE parsed.amount IS NOT NULL
  AND public.te_numeric_is_finite(parsed.amount)
  AND parsed.amount <> 0
  AND NOT EXISTS (
    SELECT 1
    FROM public.sale_payments existing
    WHERE existing.sale_id = s.id
      AND (
        existing.legacy_key = format('legacy-abono:%s:%s', s.id, a.ord)
        OR (
          NULLIF(a.entry ->> 'request_id', '') IS NOT NULL
          AND existing.request_id::text = a.entry ->> 'request_id'
        )
      )
  )
ON CONFLICT (legacy_key) WHERE legacy_key IS NOT NULL DO NOTHING;

-- Las ventas directas representan un pago por el total, no por el efectivo
-- entregado (paid_amount puede incluir cambio). created_at si es una fecha real
-- conocida del registro, no una estimacion inventada.
INSERT INTO public.sale_payments (
  sale_id, legacy_key, kind, amount, method, paid_at,
  collected_by, collected_by_email, is_estimated, source, meta
)
SELECT
  s.id,
  format('legacy-sale:%s', s.id),
  'payment',
  round(s.total, 2),
  CASE lower(s.payment_method)
    WHEN 'efectivo' THEN 'efectivo'
    WHEN 'transferencia' THEN 'transferencia'
    ELSE 'unknown'
  END,
  s.created_at,
  NULL,
  s.seller_email,
  (s.created_at IS NULL OR lower(COALESCE(s.payment_method, '')) NOT IN ('efectivo', 'transferencia')),
  'legacy_direct_sale',
  jsonb_build_object('audit_note', 'Pago derivado de una venta directa historica')
FROM public.sales s
WHERE s.origin_type = 'venta'
  AND COALESCE(s.total, 0) > 0
  AND NOT EXISTS (
    SELECT 1
    FROM public.sale_payments existing
    WHERE existing.sale_id = s.id
      AND existing.kind = 'payment'
  )
ON CONFLICT (legacy_key) WHERE legacy_key IS NOT NULL DO NOTHING;

-- Si paid_amount y el detalle historico no coinciden, se conserva el saldo que
-- usaba la aplicacion mediante un adjustment sin fecha/metodo inventados.
WITH ledger AS (
  SELECT sale_id, COALESCE(SUM(amount), 0) AS amount
  FROM public.sale_payments
  GROUP BY sale_id
), differences AS (
  SELECT
    s.id,
    round(COALESCE(s.paid_amount, 0) - COALESCE(l.amount, 0), 2) AS difference
  FROM public.sales s
  LEFT JOIN ledger l ON l.sale_id = s.id
  WHERE s.origin_type = 'apartado'
)
INSERT INTO public.sale_payments (
  sale_id, legacy_key, kind, amount, method, paid_at,
  collected_by, collected_by_email, is_estimated, source, meta
)
SELECT
  d.id,
  format('legacy-balance:%s', d.id),
  'adjustment',
  d.difference,
  'unknown',
  NULL,
  NULL,
  NULL,
  true,
  'legacy_balance_adjustment',
  jsonb_build_object(
    'audit_note', 'Diferencia historica entre paid_amount y sales.abonos; fecha y metodo desconocidos'
  )
FROM differences d
WHERE public.te_numeric_is_finite(d.difference)
  AND abs(d.difference) >= 0.005
ON CONFLICT (legacy_key) WHERE legacy_key IS NOT NULL DO NOTHING;

-- El ledger pasa a ser la fuente monetaria para apartados. Para directas se
-- conserva paid_amount porque puede representar efectivo entregado con cambio.
WITH totals AS (
  SELECT
    s.id,
    COALESCE(SUM(p.amount), 0) AS paid,
    MAX(p.paid_at) FILTER (WHERE p.amount <> 0) AS last_paid_at
  FROM public.sales s
  LEFT JOIN public.sale_payments p ON p.sale_id = s.id
  GROUP BY s.id
)
UPDATE public.sales s
SET
  paid_amount = CASE WHEN s.origin_type = 'apartado' THEN round(t.paid, 2) ELSE s.paid_amount END,
  last_payment_at = t.last_paid_at,
  status = CASE
    WHEN s.cancelled_at IS NOT NULL THEN 'cancelado'
    WHEN s.origin_type = 'apartado' AND round(t.paid, 2) < round(s.total, 2) THEN 'activo'
    ELSE 'liquidado'
  END,
  liquidated_at = CASE
    WHEN s.origin_type = 'venta' THEN COALESCE(s.liquidated_at, s.created_at)
    WHEN round(t.paid, 2) >= round(s.total, 2)
      THEN COALESCE(s.liquidated_at, t.last_paid_at)
    ELSE NULL
  END,
  type = CASE
    WHEN s.cancelled_at IS NULL
         AND s.origin_type = 'apartado'
         AND round(t.paid, 2) < round(s.total, 2)
      THEN 'apartado'
    ELSE 'venta'
  END,
  updated_at = COALESCE(
    GREATEST(s.updated_at, s.cancelled_at, t.last_paid_at, s.created_at),
    now()
  )
FROM totals t
WHERE t.id = s.id;

-- Durante la ventana entre fase 1 y fase 2 aun pueden existir pestañas PWA con
-- el JS anterior. Estos helpers mantienen origin/status/ledger coherentes para
-- INSERT/PATCH legacy. No vuelven atomico al cliente viejo; solo evitan perder
-- su dinero/auditoria hasta cerrar las policies en la fase 2.
CREATE OR REPLACE FUNCTION public.te_sync_legacy_sale_payments(p_sale_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_sale       public.sales%ROWTYPE;
  v_entry      jsonb;
  v_ord        bigint;
  v_amount     numeric;
  v_method     text;
  v_paid_at    timestamptz;
  v_ledger     numeric;
  v_difference numeric;
BEGIN
  SELECT * INTO v_sale FROM public.sales WHERE id = p_sale_id;
  IF NOT FOUND THEN RETURN; END IF;

  IF v_sale.origin_type = 'venta' AND COALESCE(v_sale.total, 0) > 0 THEN
    INSERT INTO public.sale_payments (
      sale_id, legacy_key, kind, amount, method, paid_at,
      collected_by, collected_by_email, is_estimated, source, meta
    )
    SELECT
      v_sale.id,
      format('legacy-sale:%s', v_sale.id),
      'payment',
      round(v_sale.total, 2),
      CASE lower(v_sale.payment_method)
        WHEN 'efectivo' THEN 'efectivo'
        WHEN 'transferencia' THEN 'transferencia'
        ELSE 'unknown'
      END,
      v_sale.created_at,
      NULL,
      v_sale.seller_email,
      (v_sale.created_at IS NULL OR lower(COALESCE(v_sale.payment_method, '')) NOT IN ('efectivo', 'transferencia')),
      'legacy_direct_sale',
      jsonb_build_object('audit_note', 'Capturado por trigger de compatibilidad temporal')
    WHERE NOT EXISTS (
      SELECT 1 FROM public.sale_payments p
      WHERE p.sale_id = v_sale.id AND p.kind = 'payment'
    )
    ON CONFLICT (legacy_key) WHERE legacy_key IS NOT NULL DO NOTHING;
    RETURN;
  END IF;

  IF v_sale.origin_type <> 'apartado' THEN RETURN; END IF;

  FOR v_entry, v_ord IN
    SELECT a.entry, a.ord
    FROM jsonb_array_elements(
      CASE WHEN jsonb_typeof(v_sale.abonos) = 'array' THEN v_sale.abonos ELSE '[]'::jsonb END
    ) WITH ORDINALITY AS a(entry, ord)
  LOOP
    v_amount := round(public.te_try_numeric(v_entry ->> 'amount'), 2);
    IF v_amount IS NULL OR NOT public.te_numeric_is_finite(v_amount) OR v_amount = 0 THEN CONTINUE; END IF;
    v_method := CASE lower(v_entry ->> 'method')
      WHEN 'efectivo' THEN 'efectivo'
      WHEN 'transferencia' THEN 'transferencia'
      ELSE 'unknown'
    END;
    v_paid_at := public.te_try_timestamptz(v_entry ->> 'date');

    IF NULLIF(v_entry ->> 'request_id', '') IS NOT NULL
       AND EXISTS (
         SELECT 1 FROM public.sale_payments p
         WHERE p.sale_id = v_sale.id
           AND p.request_id::text = v_entry ->> 'request_id'
       ) THEN
      CONTINUE;
    END IF;

    INSERT INTO public.sale_payments (
      sale_id, legacy_key, kind, amount, method, paid_at,
      collected_by, collected_by_email, is_estimated, source, meta
    ) VALUES (
      v_sale.id,
      format('legacy-abono:%s:%s', v_sale.id, v_ord),
      CASE WHEN v_amount < 0 THEN 'refund' ELSE 'payment' END,
      v_amount,
      v_method,
      v_paid_at,
      NULL,
      NULL,
      (v_method = 'unknown' OR v_paid_at IS NULL),
      'legacy_abono',
      jsonb_build_object(
        'ordinal', v_ord,
        'raw', v_entry,
        'audit_note', 'Capturado por trigger de compatibilidad temporal'
      )
    )
    ON CONFLICT (legacy_key) WHERE legacy_key IS NOT NULL DO NOTHING;
  END LOOP;

  SELECT round(COALESCE(SUM(amount), 0), 2)
    INTO v_ledger
  FROM public.sale_payments
  WHERE sale_id = v_sale.id;
  v_difference := round(COALESCE(v_sale.paid_amount, 0) - v_ledger, 2);

  IF public.te_numeric_is_finite(v_difference) AND abs(v_difference) >= 0.005 THEN
    INSERT INTO public.sale_payments (
      sale_id, legacy_key, kind, amount, method, paid_at,
      collected_by, collected_by_email, is_estimated, source, meta
    ) VALUES (
      v_sale.id,
      format('compat-balance:%s:v%s', v_sale.id, v_sale.version),
      'adjustment',
      v_difference,
      'unknown',
      NULL,
      NULL,
      NULL,
      true,
      'legacy_balance_adjustment',
      jsonb_build_object(
        'audit_note', 'Cambio legacy de paid_amount sin detalle equivalente; fecha y metodo desconocidos'
      )
    )
    ON CONFLICT (legacy_key) WHERE legacy_key IS NOT NULL DO NOTHING;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.te_sales_compat_before_write()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_last_payment timestamptz;
BEGIN
  IF current_setting('tresencantos.rpc_v2', true) = 'on' THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    NEW.items := public.te_snapshot_sale_items(NEW.items);
  ELSIF NEW.items IS DISTINCT FROM OLD.items THEN
    NEW.items := public.te_preserve_item_kit_snapshots(
      public.te_snapshot_sale_items(NEW.items),
      OLD.items
    );
  END IF;

  IF TG_OP = 'UPDATE' THEN
    -- created_at es la fecha de alta y nunca debe cambiar al recibir un abono.
    NEW.created_at := OLD.created_at;
    NEW.version := COALESCE(OLD.version, 0) + 1;
    NEW.origin_type := OLD.origin_type;
  ELSE
    NEW.version := COALESCE(NEW.version, 0);
  END IF;

  IF NEW.origin_type IS NULL
     OR (TG_OP = 'INSERT' AND NEW.origin_type = 'venta') THEN
    NEW.origin_type := CASE
      WHEN NEW.type = 'apartado' THEN 'apartado'
      WHEN jsonb_typeof(NEW.abonos) = 'array' AND jsonb_array_length(NEW.abonos) > 0 THEN 'apartado'
      ELSE 'venta'
    END;
  END IF;

  SELECT MAX(public.te_try_timestamptz(a.entry ->> 'date'))
    INTO v_last_payment
  FROM jsonb_array_elements(
    CASE WHEN jsonb_typeof(NEW.abonos) = 'array' THEN NEW.abonos ELSE '[]'::jsonb END
  ) AS a(entry);

  NEW.last_payment_at := COALESCE(v_last_payment, NEW.last_payment_at);
  NEW.status := CASE
    WHEN NEW.cancelled_at IS NOT NULL THEN 'cancelado'
    WHEN NEW.origin_type = 'apartado'
         AND round(COALESCE(NEW.paid_amount, 0), 2) < round(COALESCE(NEW.total, 0), 2)
      THEN 'activo'
    ELSE 'liquidado'
  END;
  NEW.type := CASE WHEN NEW.status = 'activo' THEN 'apartado' ELSE 'venta' END;

  IF NEW.origin_type = 'apartado' THEN
    NEW.liquidated_at := CASE
      WHEN NEW.status = 'liquidado' THEN COALESCE(NEW.liquidated_at, v_last_payment)
      WHEN NEW.status = 'activo' THEN NULL
      ELSE NEW.liquidated_at
    END;
  ELSIF NEW.status = 'liquidado' THEN
    NEW.liquidated_at := COALESCE(NEW.liquidated_at, NEW.created_at);
  END IF;

  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.te_sales_compat_after_write()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_product_ids bigint[];
BEGIN
  IF current_setting('tresencantos.rpc_v2', true) = 'on' THEN
    RETURN NEW;
  END IF;
  PERFORM public.te_sync_legacy_sale_payments(NEW.id);

  -- Durante la ventana de despliegue, los clientes cacheados aun escriben
  -- sales directamente. Recalcula las banderas para que un PATCH legacy que
  -- liquide/edite/cancele no deje is_apartado pegado.
  IF NEW.origin_type = 'apartado' THEN
    SELECT array_agg(d.product_id ORDER BY d.product_id)
      INTO v_product_ids
    FROM public.te_inventory_demand(NEW.items) d;

    IF COALESCE(array_length(v_product_ids, 1), 0) > 0 THEN
      PERFORM pg_advisory_xact_lock(hashtextextended('tresencantos:inventory', 0));
      PERFORM p.id FROM public.products p
      WHERE p.id = ANY(v_product_ids)
      ORDER BY p.id
      FOR UPDATE;
      PERFORM public.te_refresh_apartado_product_flags(v_product_ids);
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS te_sales_compat_before_write_trg ON public.sales;
CREATE TRIGGER te_sales_compat_before_write_trg
BEFORE INSERT OR UPDATE ON public.sales
FOR EACH ROW EXECUTE FUNCTION public.te_sales_compat_before_write();

DROP TRIGGER IF EXISTS te_sales_compat_after_write_trg ON public.sales;
CREATE TRIGGER te_sales_compat_after_write_trg
AFTER INSERT OR UPDATE ON public.sales
FOR EACH ROW EXECUTE FUNCTION public.te_sales_compat_after_write();

REVOKE ALL ON FUNCTION public.te_sync_legacy_sale_payments(bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.te_sales_compat_before_write() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.te_sales_compat_after_write() FROM PUBLIC;

-- -----------------------------------------------------------------------------
-- 5. RPC v2: alta atomica de venta/apartado
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.record_sale_atomic_v2(
  p_request_id uuid,
  p_items jsonb,
  p_total numeric,
  p_discount numeric DEFAULT 0,
  p_payment_method text DEFAULT 'efectivo',
  p_note text DEFAULT NULL,
  p_is_apartado boolean DEFAULT false,
  p_paid_amount numeric DEFAULT NULL,
  p_customer text DEFAULT NULL,
  p_due_date date DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_operation      constant text := 'record_sale_v2';
  v_cached         jsonb;
  v_response       jsonb;
  v_items          jsonb;
  v_sale_id        bigint;
  v_parent_ids     bigint[];
  v_product_ids    bigint[];
  v_subtotal       numeric;
  v_discount       numeric;
  v_total          numeric;
  v_paid           numeric;
  v_tendered       numeric;
  v_origin         text;
  v_status         text;
  v_type           text;
  v_now            timestamptz := now();
  v_abonos         jsonb;
  v_customer       text := NULLIF(btrim(p_customer), '');
  v_actor_email    text := lower(auth.jwt() ->> 'email');
  v_short_customer text;
  v_shortage       record;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'No autenticado';
  END IF;

  v_cached := public.te_rpc_replay(p_request_id, v_operation);
  IF v_cached IS NOT NULL THEN RETURN v_cached; END IF;

  PERFORM set_config('tresencantos.rpc_v2', 'on', true);

  -- Todos los RPC de inventario toman el mismo advisory lock antes de filas.
  PERFORM pg_advisory_xact_lock(hashtextextended('tresencantos:inventory', 0));

  IF jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'La venta debe tener productos';
  END IF;
  IF lower(COALESCE(p_payment_method, '')) NOT IN ('efectivo', 'transferencia') THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Metodo de pago invalido';
  END IF;
  IF p_is_apartado AND v_customer IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'El cliente es obligatorio para un apartado';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM (
      SELECT public.te_try_numeric(x.item ->> 'id') AS raw_id
      FROM jsonb_array_elements(p_items) AS x(item)
    ) q
    WHERE raw_id IS NULL OR raw_id <= 0 OR raw_id <> trunc(raw_id)
       OR raw_id > 9223372036854775807::numeric
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Hay productos con id invalido';
  END IF;

  SELECT array_agg(DISTINCT q.raw_id::bigint ORDER BY q.raw_id::bigint)
    INTO v_parent_ids
  FROM (
    SELECT public.te_try_numeric(x.item ->> 'id') AS raw_id
    FROM jsonb_array_elements(p_items) AS x(item)
  ) q;

  PERFORM p.id FROM public.products p
  WHERE p.id = ANY(v_parent_ids)
  ORDER BY p.id
  FOR UPDATE;

  IF (SELECT COUNT(*) FROM public.products p WHERE p.id = ANY(v_parent_ids))
     <> COALESCE(array_length(v_parent_ids, 1), 0) THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'Uno o mas productos ya no existen';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.products p
    WHERE p.id = ANY(v_parent_ids) AND COALESCE(p.is_archived, false)
  ) THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = 'Un producto fue archivado; recarga la caja antes de cobrar';
  END IF;

  v_items := public.te_snapshot_sale_items(p_items);

  SELECT COALESCE(SUM((x.item ->> 'subtotal')::numeric), 0)
    INTO v_subtotal
  FROM jsonb_array_elements(v_items) AS x(item);

  v_discount := round(COALESCE(p_discount, 0), 2);
  IF NOT public.te_numeric_is_finite(v_discount)
     OR v_discount < 0 OR v_discount > v_subtotal THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Descuento invalido';
  END IF;
  v_total := round(v_subtotal - v_discount, 2);
  IF v_total <= 0 THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'El total debe ser mayor a cero';
  END IF;
  IF NOT public.te_numeric_is_finite(p_total)
     OR abs(round(p_total, 2) - v_total) >= 0.005 THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = format('El total cambio: esperado %s, recibido %s', v_total, COALESCE(p_total, 0));
  END IF;

  IF p_is_apartado THEN
    v_paid := round(COALESCE(p_paid_amount, 0), 2);
    IF NOT public.te_numeric_is_finite(v_paid)
       OR v_paid < 0 OR v_paid > v_total THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'El anticipo no puede superar el total';
    END IF;
    v_tendered := v_paid;
    v_origin := 'apartado';
    IF v_paid >= v_total THEN
      v_status := 'liquidado'; v_type := 'venta';
    ELSE
      v_status := 'activo'; v_type := 'apartado';
    END IF;
  ELSE
    v_paid := v_total;
    v_tendered := round(COALESCE(p_paid_amount, v_total), 2);
    IF NOT public.te_numeric_is_finite(v_tendered) OR v_tendered < v_total THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'El pago no cubre el total';
    END IF;
    v_origin := 'venta'; v_status := 'liquidado'; v_type := 'venta';
  END IF;

  SELECT array_agg(d.product_id ORDER BY d.product_id)
    INTO v_product_ids
  FROM public.te_inventory_demand(v_items) d;

  PERFORM p.id FROM public.products p
  WHERE p.id = ANY(v_product_ids)
  ORDER BY p.id
  FOR UPDATE;

  IF (SELECT COUNT(*) FROM public.products p WHERE p.id = ANY(v_product_ids))
     <> COALESCE(array_length(v_product_ids, 1), 0) THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'Un componente del kit ya no existe';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.products p
    WHERE p.id = ANY(v_product_ids) AND COALESCE(p.is_archived, false)
  ) THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = 'Un producto o componente fue archivado; recarga la caja antes de cobrar';
  END IF;

  SELECT d.product_id, d.required_qty, COALESCE(p.stock, 0) AS stock
    INTO v_shortage
  FROM public.te_inventory_demand(v_items) d
  JOIN public.products p ON p.id = d.product_id
  WHERE COALESCE(p.stock, 0) < d.required_qty
  ORDER BY d.product_id
  LIMIT 1;
  IF FOUND THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = format('Sin stock suficiente para producto id=%s (disponible %s, requerido %s)',
                       v_shortage.product_id, v_shortage.stock, v_shortage.required_qty);
  END IF;

  v_abonos := CASE
    WHEN p_is_apartado AND v_paid > 0 THEN jsonb_build_array(jsonb_build_object(
      'amount', v_paid,
      'method', lower(p_payment_method),
      'date', v_now,
      'request_id', p_request_id,
      'collected_by', v_actor_email,
      'kind', 'payment'
    ))
    ELSE NULL
  END;

  INSERT INTO public.sales (
    total, items, discount, payment_method, note, type, paid_amount,
    customer, due_date, seller_email, abonos,
    origin_type, status, liquidated_at, last_payment_at, updated_at, version
  ) VALUES (
    v_total,
    v_items,
    NULLIF(v_discount, 0),
    lower(p_payment_method),
    NULLIF(btrim(p_note), ''),
    v_type,
    v_tendered,
    v_customer,
    CASE WHEN p_is_apartado THEN p_due_date ELSE NULL END,
    v_actor_email,
    v_abonos,
    v_origin,
    v_status,
    CASE WHEN v_status = 'liquidado' THEN v_now ELSE NULL END,
    CASE WHEN (NOT p_is_apartado) OR v_paid > 0 THEN v_now ELSE NULL END,
    v_now,
    0
  )
  RETURNING id INTO v_sale_id;

  INSERT INTO public.sale_payments (
    sale_id, request_id, kind, amount, method, paid_at,
    collected_by, collected_by_email, is_estimated, source, meta
  )
  SELECT
    v_sale_id,
    p_request_id,
    'payment',
    CASE WHEN p_is_apartado THEN v_paid ELSE v_total END,
    lower(p_payment_method),
    v_now,
    auth.uid(),
    v_actor_email,
    false,
    CASE WHEN p_is_apartado THEN 'rpc_apartado_initial' ELSE 'rpc_direct_sale' END,
    jsonb_build_object('origin_type', v_origin)
  WHERE (NOT p_is_apartado) OR v_paid > 0;

  WITH demand AS (
    SELECT * FROM public.te_inventory_demand(v_items)
  )
  UPDATE public.products p
  SET stock = COALESCE(p.stock, 0) - d.required_qty
  FROM demand d
  WHERE p.id = d.product_id;

  PERFORM public.te_refresh_apartado_product_flags(v_product_ids);

  v_short_customer := COALESCE(split_part(v_customer, ' · ', 1), 'cliente');
  IF p_is_apartado AND v_status = 'activo' THEN
    PERFORM public.te_log_activity(
      'apartado_nuevo',
      format('Apartado de %s — $%s', v_short_customer, v_total),
      jsonb_build_object(
        'id', v_sale_id, 'customer', v_short_customer, 'total', v_total,
        'anticipo', v_paid, 'pendiente', v_total - v_paid,
        'dueDate', p_due_date, 'items', jsonb_array_length(v_items),
        'itemIds', to_jsonb(v_parent_ids), 'itemsDetail', v_items,
        'request_id', p_request_id
      )
    );
  ELSIF p_is_apartado THEN
    PERFORM public.te_log_activity(
      'apartado_liquidado',
      format('Apartado pagado completo de %s — $%s', v_short_customer, v_total),
      jsonb_build_object(
        'id', v_sale_id, 'customer', v_short_customer, 'total', v_total,
        'method', lower(p_payment_method), 'items', jsonb_array_length(v_items),
        'itemIds', to_jsonb(v_parent_ids), 'itemsDetail', v_items,
        'request_id', p_request_id
      )
    );
  ELSE
    PERFORM public.te_log_activity(
      'venta',
      format('Cobro $%s — %s producto(s)', v_total, jsonb_array_length(v_items)),
      jsonb_build_object(
        'id', v_sale_id, 'total', v_total, 'method', lower(p_payment_method),
        'discount', v_discount, 'items', jsonb_array_length(v_items),
        'itemIds', to_jsonb(v_parent_ids), 'itemsDetail', v_items,
        'request_id', p_request_id
      )
    );
  END IF;

  v_response := jsonb_build_object(
    'ok', true,
    'operation', v_operation,
    'request_id', p_request_id,
    'liquidated', (v_status = 'liquidado'),
    'sale', jsonb_build_object(
      'id', v_sale_id,
      'origin_type', v_origin,
      'status', v_status,
      'type', v_type,
      'total', v_total,
      'paid_amount', CASE WHEN p_is_apartado THEN v_paid ELSE v_tendered END,
      'remaining', CASE WHEN p_is_apartado THEN v_total - v_paid ELSE 0 END,
      'liquidated_at', CASE WHEN v_status = 'liquidado' THEN v_now ELSE NULL END,
      'version', 0
    ),
    'products', public.te_products_state(v_product_ids)
  );

  PERFORM public.te_rpc_store(p_request_id, v_operation, v_sale_id, v_response);
  RETURN v_response;
END;
$$;

-- -----------------------------------------------------------------------------
-- 6. RPC v2: abono o liquidacion
-- p_amount NULL cobra exactamente el saldo actual bajo FOR UPDATE.
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.record_apartado_payment_atomic(
  p_request_id uuid,
  p_sale_id bigint,
  p_method text,
  p_amount numeric,
  p_expected_version bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_operation   constant text := 'apartado_payment_v2';
  v_cached      jsonb;
  v_response    jsonb;
  v_sale        public.sales%ROWTYPE;
  v_now         timestamptz := now();
  v_amount      numeric;
  v_paid        numeric;
  v_remaining   numeric;
  v_is_final    boolean;
  v_payment     jsonb;
  v_product_ids bigint[];
  v_customer    text;
  v_actor_email text := lower(auth.jwt() ->> 'email');
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'No autenticado';
  END IF;
  IF lower(COALESCE(p_method, '')) NOT IN ('efectivo', 'transferencia') THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Metodo de pago invalido';
  END IF;

  v_cached := public.te_rpc_replay(p_request_id, v_operation);
  IF v_cached IS NOT NULL THEN RETURN v_cached; END IF;
  PERFORM set_config('tresencantos.rpc_v2', 'on', true);
  PERFORM pg_advisory_xact_lock(hashtextextended('tresencantos:inventory', 0));

  SELECT * INTO v_sale
  FROM public.sales
  WHERE id = p_sale_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'Apartado no encontrado';
  END IF;
  IF p_expected_version IS NULL OR p_expected_version <> v_sale.version THEN
    RAISE EXCEPTION USING
      ERRCODE = '40001',
      MESSAGE = 'El apartado cambio en otro dispositivo; vuelve a cargarlo';
  END IF;
  IF v_sale.cancelled_at IS NOT NULL OR v_sale.status = 'cancelado' THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'El apartado esta cancelado';
  END IF;
  IF v_sale.origin_type <> 'apartado' THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'El registro no es un apartado';
  END IF;
  IF v_sale.status <> 'activo' OR v_sale.type <> 'apartado' THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'El apartado ya esta liquidado';
  END IF;

  v_remaining := round(v_sale.total - COALESCE(v_sale.paid_amount, 0), 2);
  IF v_remaining <= 0 THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'El apartado no tiene saldo pendiente; requiere reconciliacion';
  END IF;
  v_amount := CASE WHEN p_amount IS NULL THEN v_remaining ELSE round(p_amount, 2) END;
  IF NOT public.te_numeric_is_finite(v_amount)
     OR v_amount <= 0 OR v_amount > v_remaining THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = format('Abono invalido; saldo actual $%s', v_remaining);
  END IF;

  v_paid := round(COALESCE(v_sale.paid_amount, 0) + v_amount, 2);
  v_is_final := v_paid >= round(v_sale.total, 2);
  IF v_is_final THEN v_paid := round(v_sale.total, 2); END IF;

  v_payment := jsonb_build_object(
    'amount', v_amount,
    'method', lower(p_method),
    'date', v_now,
    'request_id', p_request_id,
    'collected_by', v_actor_email,
    'kind', 'payment'
  );

  INSERT INTO public.sale_payments (
    sale_id, request_id, kind, amount, method, paid_at,
    collected_by, collected_by_email, is_estimated, source, meta
  ) VALUES (
    p_sale_id, p_request_id, 'payment', v_amount, lower(p_method), v_now,
    auth.uid(), v_actor_email, false,
    CASE WHEN v_is_final THEN 'rpc_apartado_liquidation' ELSE 'rpc_apartado_payment' END,
    jsonb_build_object('remaining_before', v_remaining)
  );

  UPDATE public.sales
  SET
    paid_amount = v_paid,
    abonos = COALESCE(
      CASE WHEN jsonb_typeof(abonos) = 'array' THEN abonos ELSE '[]'::jsonb END,
      '[]'::jsonb
    ) || jsonb_build_array(v_payment),
    payment_method = CASE WHEN v_is_final THEN lower(p_method) ELSE payment_method END,
    type = CASE WHEN v_is_final THEN 'venta' ELSE 'apartado' END,
    status = CASE WHEN v_is_final THEN 'liquidado' ELSE 'activo' END,
    liquidated_at = CASE WHEN v_is_final THEN v_now ELSE NULL END,
    last_payment_at = v_now,
    updated_at = v_now,
    version = version + 1
  WHERE id = p_sale_id;

  IF v_is_final THEN
    SELECT array_agg(d.product_id ORDER BY d.product_id)
      INTO v_product_ids
    FROM public.te_inventory_demand(v_sale.items) d;
    PERFORM p.id FROM public.products p
    WHERE p.id = ANY(v_product_ids)
    ORDER BY p.id
    FOR UPDATE;
    PERFORM public.te_refresh_apartado_product_flags(v_product_ids);
  END IF;

  v_customer := COALESCE(split_part(v_sale.customer, ' · ', 1), 'cliente');
  IF v_is_final THEN
    PERFORM public.te_log_activity(
      'apartado_liquidado',
      format('Liquido apartado de %s — $%s', v_customer, v_amount),
      jsonb_build_object(
        'id', p_sale_id, 'customer', v_customer, 'amount', v_amount,
        'total', v_sale.total, 'method', lower(p_method),
        'itemsDetail', v_sale.items, 'request_id', p_request_id
      )
    );
  ELSE
    PERFORM public.te_log_activity(
      'apartado_abono',
      format('Abono de $%s a %s', v_amount, v_customer),
      jsonb_build_object(
        'id', p_sale_id, 'customer', v_customer, 'amount', v_amount,
        'method', lower(p_method), 'request_id', p_request_id
      )
    );
  END IF;

  v_response := jsonb_build_object(
    'ok', true,
    'operation', v_operation,
    'request_id', p_request_id,
    'liquidated', v_is_final,
    'sale', jsonb_build_object(
      'id', p_sale_id,
      'type', CASE WHEN v_is_final THEN 'venta' ELSE 'apartado' END,
      'origin_type', 'apartado',
      'status', CASE WHEN v_is_final THEN 'liquidado' ELSE 'activo' END,
      'total', v_sale.total,
      'paid_amount', v_paid,
      'remaining', round(v_sale.total - v_paid, 2),
      'liquidated_at', CASE WHEN v_is_final THEN v_now ELSE NULL END,
      'version', v_sale.version + 1
    ),
    'payment', v_payment,
    'products', CASE WHEN v_is_final THEN public.te_products_state(v_product_ids) ELSE '[]'::jsonb END
  );

  PERFORM public.te_rpc_store(p_request_id, v_operation, p_sale_id, v_response);
  RETURN v_response;
END;
$$;

-- -----------------------------------------------------------------------------
-- 7. RPC v2: editar productos/precios de un apartado
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.edit_apartado_atomic(
  p_request_id uuid,
  p_sale_id bigint,
  p_items jsonb,
  p_expected_version bigint,
  p_discount numeric DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_operation   constant text := 'edit_apartado_v2';
  v_cached      jsonb;
  v_response    jsonb;
  v_sale        public.sales%ROWTYPE;
  v_items       jsonb;
  v_parent_ids  bigint[];
  v_product_ids bigint[];
  v_subtotal    numeric;
  v_discount    numeric;
  v_total       numeric;
  v_paid        numeric;
  v_now         timestamptz := now();
  v_is_final    boolean;
  v_shortage    record;
  v_customer    text;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'No autenticado';
  END IF;
  IF NOT public.te_has_permission('canEditApartado') THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'Sin permiso para editar apartados';
  END IF;

  v_cached := public.te_rpc_replay(p_request_id, v_operation);
  IF v_cached IS NOT NULL THEN RETURN v_cached; END IF;
  PERFORM set_config('tresencantos.rpc_v2', 'on', true);
  PERFORM pg_advisory_xact_lock(hashtextextended('tresencantos:inventory', 0));

  SELECT * INTO v_sale
  FROM public.sales
  WHERE id = p_sale_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'Apartado no encontrado';
  END IF;
  IF p_expected_version IS NULL OR p_expected_version <> v_sale.version THEN
    RAISE EXCEPTION USING
      ERRCODE = '40001',
      MESSAGE = 'El apartado cambio en otro dispositivo; vuelve a cargarlo';
  END IF;
  IF v_sale.origin_type <> 'apartado' OR v_sale.status <> 'activo' OR v_sale.cancelled_at IS NOT NULL THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'Solo se puede editar un apartado activo';
  END IF;
  PERFORM public.te_assert_authoritative_inventory_snapshot(v_sale.items, 'editar el inventario del apartado');

  IF jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'El apartado debe conservar al menos un producto';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM (
      SELECT public.te_try_numeric(x.item ->> 'id') AS raw_id
      FROM jsonb_array_elements(p_items) AS x(item)
    ) q
    WHERE raw_id IS NULL OR raw_id <= 0 OR raw_id <> trunc(raw_id)
       OR raw_id > 9223372036854775807::numeric
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Hay productos con id invalido';
  END IF;

  SELECT array_agg(DISTINCT q.raw_id::bigint ORDER BY q.raw_id::bigint)
    INTO v_parent_ids
  FROM (
    SELECT public.te_try_numeric(x.item ->> 'id') AS raw_id
    FROM jsonb_array_elements(p_items) AS x(item)
  ) q;

  PERFORM p.id FROM public.products p
  WHERE p.id = ANY(v_parent_ids)
  ORDER BY p.id
  FOR UPDATE;
  IF (SELECT COUNT(*) FROM public.products p WHERE p.id = ANY(v_parent_ids))
     <> COALESCE(array_length(v_parent_ids, 1), 0) THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'Uno o mas productos ya no existen';
  END IF;

  -- Para productos que ya pertenecian al apartado, conserva el snapshot del
  -- kit guardado en la fila bloqueada. Solo productos nuevos toman la
  -- composicion actual; nunca se acepta kit_items enviado por el navegador.
  v_items := public.te_preserve_item_kit_snapshots(
    public.te_snapshot_sale_items(p_items),
    v_sale.items
  );

  -- Un producto padre archivado puede conservarse o reducirse para resolver
  -- un apartado previo, pero nunca agregarse/aumentarse desde un carrito stale.
  IF EXISTS (
    WITH old_parent AS (
      SELECT
        public.te_require_positive_bigint(i.item ->> 'id', 'id de producto') AS product_id,
        SUM(public.te_require_positive_bigint(COALESCE(i.item ->> 'qty', '1'), 'cantidad de producto')) AS qty
      FROM jsonb_array_elements(v_sale.items) i(item)
      GROUP BY 1
    ), new_parent AS (
      SELECT
        public.te_require_positive_bigint(i.item ->> 'id', 'id de producto') AS product_id,
        SUM(public.te_require_positive_bigint(COALESCE(i.item ->> 'qty', '1'), 'cantidad de producto')) AS qty
      FROM jsonb_array_elements(v_items) i(item)
      GROUP BY 1
    )
    SELECT 1
    FROM new_parent n
    LEFT JOIN old_parent o USING (product_id)
    JOIN public.products p ON p.id = n.product_id
    WHERE n.qty > COALESCE(o.qty, 0)
      AND COALESCE(p.is_archived, false)
  ) THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = 'No se puede agregar o aumentar un producto archivado; recarga el inventario';
  END IF;

  -- Subtotales no dependen del snapshot preservado, pero se recalculan tras la
  -- fusion para mantener una sola fuente de verdad en este bloque.
  SELECT COALESCE(SUM((x.item ->> 'subtotal')::numeric), 0)
    INTO v_subtotal
  FROM jsonb_array_elements(v_items) AS x(item);

  v_discount := round(COALESCE(p_discount, v_sale.discount, 0), 2);
  IF NOT public.te_numeric_is_finite(v_discount)
     OR v_discount < 0 OR v_discount > v_subtotal THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Descuento invalido';
  END IF;
  v_total := round(v_subtotal - v_discount, 2);
  v_paid := round(COALESCE(v_sale.paid_amount, 0), 2);
  IF NOT public.te_numeric_is_finite(v_total)
     OR NOT public.te_numeric_is_finite(v_paid)
     OR v_total <= 0 THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'El total debe ser mayor a cero';
  END IF;
  IF v_total < v_paid THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = format('El total ($%s) no puede ser menor a lo pagado ($%s); registra una devolucion explicita', v_total, v_paid);
  END IF;
  v_is_final := v_paid >= v_total;

  SELECT array_agg(id ORDER BY id)
    INTO v_product_ids
  FROM (
    SELECT product_id AS id FROM public.te_inventory_demand(v_sale.items)
    UNION
    SELECT product_id AS id FROM public.te_inventory_demand(v_items)
  ) ids;

  PERFORM p.id FROM public.products p
  WHERE p.id = ANY(v_product_ids)
  ORDER BY p.id
  FOR UPDATE;
  IF (SELECT COUNT(*) FROM public.products p WHERE p.id = ANY(v_product_ids))
     <> COALESCE(array_length(v_product_ids, 1), 0) THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'Un producto o componente historico ya no existe';
  END IF;

  IF EXISTS (
    WITH old_demand AS (
      SELECT * FROM public.te_inventory_demand(v_sale.items)
    ), new_demand AS (
      SELECT * FROM public.te_inventory_demand(v_items)
    ), delta AS (
      SELECT
        COALESCE(n.product_id, o.product_id) AS product_id,
        COALESCE(n.required_qty, 0) - COALESCE(o.required_qty, 0) AS qty
      FROM old_demand o
      FULL JOIN new_demand n USING (product_id)
    )
    SELECT 1
    FROM delta d
    JOIN public.products p ON p.id = d.product_id
    WHERE d.qty > 0 AND COALESCE(p.is_archived, false)
  ) THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = 'No se puede aumentar inventario reservado de un producto o componente archivado';
  END IF;

  WITH old_demand AS (
    SELECT * FROM public.te_inventory_demand(v_sale.items)
  ), new_demand AS (
    SELECT * FROM public.te_inventory_demand(v_items)
  ), delta AS (
    SELECT
      COALESCE(n.product_id, o.product_id) AS product_id,
      COALESCE(n.required_qty, 0) - COALESCE(o.required_qty, 0) AS qty
    FROM old_demand o
    FULL JOIN new_demand n USING (product_id)
  )
  SELECT d.product_id, d.qty, COALESCE(p.stock, 0) AS stock
    INTO v_shortage
  FROM delta d
  JOIN public.products p ON p.id = d.product_id
  WHERE d.qty > 0 AND COALESCE(p.stock, 0) < d.qty
  ORDER BY d.product_id
  LIMIT 1;
  IF FOUND THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = format('Sin stock para aumentar producto id=%s (disponible %s, requerido %s)',
                       v_shortage.product_id, v_shortage.stock, v_shortage.qty);
  END IF;

  WITH old_demand AS (
    SELECT * FROM public.te_inventory_demand(v_sale.items)
  ), new_demand AS (
    SELECT * FROM public.te_inventory_demand(v_items)
  ), delta AS (
    SELECT
      COALESCE(n.product_id, o.product_id) AS product_id,
      COALESCE(n.required_qty, 0) - COALESCE(o.required_qty, 0) AS qty
    FROM old_demand o
    FULL JOIN new_demand n USING (product_id)
  )
  UPDATE public.products p
  SET stock = COALESCE(p.stock, 0) - d.qty
  FROM delta d
  WHERE p.id = d.product_id AND d.qty <> 0;

  UPDATE public.sales
  SET
    items = v_items,
    total = v_total,
    discount = NULLIF(v_discount, 0),
    type = CASE WHEN v_is_final THEN 'venta' ELSE 'apartado' END,
    status = CASE WHEN v_is_final THEN 'liquidado' ELSE 'activo' END,
    liquidated_at = CASE WHEN v_is_final THEN v_now ELSE NULL END,
    updated_at = v_now,
    version = version + 1
  WHERE id = p_sale_id;

  PERFORM public.te_refresh_apartado_product_flags(v_product_ids);

  v_customer := COALESCE(split_part(v_sale.customer, ' · ', 1), 'cliente');
  PERFORM public.te_log_activity(
    'apartado_editado',
    format('Edito apartado de %s — nuevo total $%s', v_customer, v_total),
    jsonb_build_object(
      'id', p_sale_id, 'customer', v_customer, 'total', v_total,
      'discount', v_discount, 'itemsDetail', v_items, 'request_id', p_request_id
    )
  );
  IF v_is_final THEN
    PERFORM public.te_log_activity(
      'apartado_liquidado',
      format('Apartado de %s quedo liquidado al editar el total', v_customer),
      jsonb_build_object(
        'id', p_sale_id, 'customer', v_customer, 'total', v_total,
        'amount', 0, 'no_cash_movement', true, 'itemsDetail', v_items,
        'request_id', p_request_id
      )
    );
  END IF;

  v_response := jsonb_build_object(
    'ok', true,
    'operation', v_operation,
    'request_id', p_request_id,
    'liquidated', v_is_final,
    'sale', jsonb_build_object(
      'id', p_sale_id,
      'origin_type', 'apartado',
      'type', CASE WHEN v_is_final THEN 'venta' ELSE 'apartado' END,
      'status', CASE WHEN v_is_final THEN 'liquidado' ELSE 'activo' END,
      'total', v_total,
      'paid_amount', v_paid,
      'remaining', v_total - v_paid,
      'liquidated_at', CASE WHEN v_is_final THEN v_now ELSE NULL END,
      'version', v_sale.version + 1,
      'items', v_items,
      'discount', NULLIF(v_discount, 0)
    ),
    'products', public.te_products_state(v_product_ids)
  );

  PERFORM public.te_rpc_store(p_request_id, v_operation, p_sale_id, v_response);
  RETURN v_response;
END;
$$;

-- -----------------------------------------------------------------------------
-- 8. RPC v2: cancelar y devolver automaticamente el saldo monetario
-- -----------------------------------------------------------------------------

-- Devuelve el saldo neto sin inventar un metodo: reparte la devolucion entre
-- los metodos originales con saldo positivo. Una linea unknown permanece
-- explicitamente unknown y se marca estimada.
CREATE OR REPLACE FUNCTION public.te_refund_sale_balance(
  p_sale_id bigint,
  p_request_id uuid,
  p_source text,
  p_reason text,
  p_paid_at timestamptz
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_total_remaining numeric;
  v_take            numeric;
  v_line            smallint := 0;
  v_method          record;
  v_refunds         jsonb := '[]'::jsonb;
  v_entry           jsonb;
  v_actor_email     text := lower(auth.jwt() ->> 'email');
BEGIN
  SELECT round(GREATEST(COALESCE(SUM(amount), 0), 0), 2)
    INTO v_total_remaining
  FROM public.sale_payments
  WHERE sale_id = p_sale_id;

  IF v_total_remaining <= 0 THEN
    RETURN v_refunds;
  END IF;

  FOR v_method IN
    SELECT method, round(SUM(amount), 2) AS balance
    FROM public.sale_payments
    WHERE sale_id = p_sale_id
    GROUP BY method
    HAVING round(SUM(amount), 2) > 0
    ORDER BY CASE method WHEN 'efectivo' THEN 1 WHEN 'transferencia' THEN 2 ELSE 3 END
  LOOP
    EXIT WHEN v_total_remaining <= 0;
    v_take := LEAST(v_method.balance, v_total_remaining);
    IF v_take <= 0 THEN CONTINUE; END IF;
    v_line := v_line + 1;

    v_entry := jsonb_build_object(
      'amount', -v_take,
      'method', v_method.method,
      'date', p_paid_at,
      'request_id', p_request_id,
      'request_line', v_line,
      'collected_by', v_actor_email,
      'kind', 'refund',
      'reason', NULLIF(btrim(p_reason), '')
    );

    INSERT INTO public.sale_payments (
      sale_id, request_id, request_line, kind, amount, method, paid_at,
      collected_by, collected_by_email, is_estimated, source, meta
    ) VALUES (
      p_sale_id, p_request_id, v_line, 'refund', -v_take, v_method.method, p_paid_at,
      auth.uid(), v_actor_email, v_method.method = 'unknown', p_source,
      jsonb_build_object('reason', NULLIF(btrim(p_reason), ''))
    );

    v_refunds := v_refunds || jsonb_build_array(v_entry);
    v_total_remaining := round(v_total_remaining - v_take, 2);
  END LOOP;

  IF v_total_remaining > 0 THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = 'No se pudo distribuir completamente la devolucion por metodo original';
  END IF;

  RETURN v_refunds;
END;
$$;

REVOKE ALL ON FUNCTION public.te_refund_sale_balance(bigint, uuid, text, text, timestamptz) FROM PUBLIC;

-- Compatibilidad temporal para clientes viejos que cancelaban con DELETE.
-- El FK del ledger nunca permite borrar la evidencia: se convierte el DELETE
-- en cancelacion logica y se registra el reembolso, sin volver a tocar stock
-- porque ese cliente ya lo restaura mediante sus PATCH historicos.
CREATE OR REPLACE FUNCTION public.te_sales_compat_before_delete()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_request_id    uuid := gen_random_uuid();
  v_now           timestamptz := now();
  v_refunds       jsonb := '[]'::jsonb;
  v_refund_amount numeric := 0;
  v_previous_mode text := current_setting('tresencantos.rpc_v2', true);
  v_customer      text := COALESCE(split_part(OLD.customer, ' · ', 1), 'cliente');
  v_item_count    integer := CASE
    WHEN jsonb_typeof(OLD.items) = 'array' THEN jsonb_array_length(OLD.items)
    ELSE 0
  END;
BEGIN
  IF current_setting('tresencantos.rpc_v2', true) = 'on' THEN
    RETURN OLD;
  END IF;
  IF OLD.cancelled_at IS NOT NULL OR OLD.status = 'cancelado' THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = 'La venta ya esta cancelada; recarga antes de restaurar stock';
  END IF;

  v_refunds := public.te_refund_sale_balance(
    OLD.id, v_request_id, 'legacy_delete_refund', 'Cancelacion desde cliente legacy', v_now
  );
  SELECT round(COALESCE(SUM(abs((e.entry ->> 'amount')::numeric)), 0), 2)
    INTO v_refund_amount
  FROM jsonb_array_elements(v_refunds) AS e(entry);

  -- Evita que el UPDATE interno vuelva a entrar a los triggers de compat.
  PERFORM set_config('tresencantos.rpc_v2', 'on', true);
  UPDATE public.sales
  SET
    cancelled_at = v_now,
    type = 'venta',
    status = 'cancelado',
    paid_amount = CASE WHEN v_refund_amount > 0 THEN 0 ELSE paid_amount END,
    abonos = CASE
      WHEN jsonb_array_length(v_refunds) > 0 THEN
        (CASE WHEN jsonb_typeof(abonos) = 'array' THEN abonos ELSE '[]'::jsonb END) || v_refunds
      ELSE abonos
    END,
    last_payment_at = CASE WHEN jsonb_array_length(v_refunds) > 0 THEN v_now ELSE last_payment_at END,
    updated_at = v_now,
    version = version + 1
  WHERE id = OLD.id;

  PERFORM public.te_log_activity(
    CASE WHEN OLD.origin_type = 'apartado' THEN 'apartado_cancelado' ELSE 'venta_cancelada' END,
    CASE
      WHEN OLD.origin_type = 'apartado'
        THEN format('Cancelo apartado legacy de %s — $%s', v_customer, OLD.total)
      ELSE format('Cancelo venta legacy de $%s — %s producto(s)', OLD.total, v_item_count)
    END,
    jsonb_build_object(
      'id', OLD.id, 'customer', v_customer, 'total', OLD.total,
      'refund', v_refund_amount, 'refunds', v_refunds,
      'reason', 'Cancelacion desde cliente legacy',
      'items', v_item_count, 'itemsDetail', OLD.items,
      'legacy_compat', true, 'request_id', v_request_id
    )
  );

  PERFORM set_config(
    'tresencantos.rpc_v2',
    CASE WHEN v_previous_mode = 'on' THEN 'on' ELSE 'off' END,
    true
  );
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS te_sales_compat_before_delete_trg ON public.sales;
CREATE TRIGGER te_sales_compat_before_delete_trg
BEFORE DELETE ON public.sales
FOR EACH ROW EXECUTE FUNCTION public.te_sales_compat_before_delete();

REVOKE ALL ON FUNCTION public.te_sales_compat_before_delete() FROM PUBLIC;

CREATE OR REPLACE FUNCTION public.cancel_sale_atomic(
  p_request_id uuid,
  p_sale_id bigint,
  p_reason text,
  p_expected_version bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_operation     constant text := 'cancel_sale_v2';
  v_cached        jsonb;
  v_response      jsonb;
  v_sale          public.sales%ROWTYPE;
  v_now           timestamptz := now();
  v_product_ids   bigint[];
  v_refund_amount numeric := 0;
  v_refund_entries jsonb := '[]'::jsonb;
  v_customer      text;
  v_item_count    integer;
  v_actor_email   text := lower(auth.jwt() ->> 'email');
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'No autenticado';
  END IF;

  v_cached := public.te_rpc_replay(p_request_id, v_operation);
  IF v_cached IS NOT NULL THEN RETURN v_cached; END IF;
  PERFORM set_config('tresencantos.rpc_v2', 'on', true);
  PERFORM pg_advisory_xact_lock(hashtextextended('tresencantos:inventory', 0));

  SELECT * INTO v_sale
  FROM public.sales
  WHERE id = p_sale_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'Venta no encontrada';
  END IF;
  IF p_expected_version IS NULL OR p_expected_version <> v_sale.version THEN
    RAISE EXCEPTION USING
      ERRCODE = '40001',
      MESSAGE = 'La venta cambio en otro dispositivo; vuelve a cargarla';
  END IF;

  IF v_sale.cancelled_at IS NOT NULL OR v_sale.status = 'cancelado' THEN
    v_response := jsonb_build_object(
      'ok', true, 'operation', v_operation, 'request_id', p_request_id,
      'already_cancelled', true,
      'sale', jsonb_build_object(
        'id', p_sale_id, 'type', 'venta', 'status', 'cancelado',
        'cancelled_at', v_sale.cancelled_at, 'version', v_sale.version
      ),
      'products', '[]'::jsonb
    );
    PERFORM public.te_rpc_store(p_request_id, v_operation, p_sale_id, v_response);
    RETURN v_response;
  END IF;

  IF v_sale.origin_type = 'apartado' AND v_sale.status = 'activo' THEN
    IF NOT (public.te_has_permission('canEditApartado') OR public.te_has_permission('canCancelSale')) THEN
      RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'Sin permiso para cancelar este apartado';
    END IF;
  ELSIF NOT public.te_has_permission('canCancelSale') THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'Sin permiso para cancelar ventas';
  END IF;

  PERFORM public.te_assert_authoritative_inventory_snapshot(v_sale.items, 'cancelar y restaurar stock');

  SELECT array_agg(d.product_id ORDER BY d.product_id)
    INTO v_product_ids
  FROM public.te_inventory_demand(v_sale.items) d;

  PERFORM p.id FROM public.products p
  WHERE p.id = ANY(v_product_ids)
  ORDER BY p.id
  FOR UPDATE;
  IF (SELECT COUNT(*) FROM public.products p WHERE p.id = ANY(v_product_ids))
     <> COALESCE(array_length(v_product_ids, 1), 0) THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'Un producto historico ya no existe; no se cancelo nada';
  END IF;

  -- La UI promete devolucion al cancelar. Siempre devuelve el neto recibido,
  -- separado por sus metodos originales; si el neto es cero no crea movimientos.
  v_refund_entries := public.te_refund_sale_balance(
    p_sale_id, p_request_id, 'rpc_sale_cancellation_refund', p_reason, v_now
  );
  SELECT round(COALESCE(SUM(abs((e.entry ->> 'amount')::numeric)), 0), 2)
    INTO v_refund_amount
  FROM jsonb_array_elements(v_refund_entries) AS e(entry);

  WITH demand AS (
    SELECT * FROM public.te_inventory_demand(v_sale.items)
  )
  UPDATE public.products p
  SET stock = COALESCE(p.stock, 0) + d.required_qty,
      out_of_stock = false
  FROM demand d
  WHERE p.id = d.product_id;

  UPDATE public.sales
  SET
    cancelled_at = v_now,
    type = 'venta',
    status = 'cancelado',
    paid_amount = CASE WHEN v_refund_amount > 0 THEN 0 ELSE paid_amount END,
    abonos = CASE
      WHEN jsonb_array_length(v_refund_entries) > 0 THEN
        (CASE WHEN jsonb_typeof(abonos) = 'array' THEN abonos ELSE '[]'::jsonb END)
        || v_refund_entries
      ELSE abonos
    END,
    last_payment_at = CASE WHEN jsonb_array_length(v_refund_entries) > 0 THEN v_now ELSE last_payment_at END,
    updated_at = v_now,
    version = version + 1
  WHERE id = p_sale_id;

  PERFORM public.te_refresh_apartado_product_flags(v_product_ids);

  v_customer := COALESCE(split_part(v_sale.customer, ' · ', 1), 'cliente');
  v_item_count := CASE WHEN jsonb_typeof(v_sale.items) = 'array' THEN jsonb_array_length(v_sale.items) ELSE 0 END;

  IF v_sale.origin_type = 'apartado' THEN
    PERFORM public.te_log_activity(
      'apartado_cancelado',
      format('Cancelo apartado de %s — $%s', v_customer, v_sale.total),
      jsonb_build_object(
        'id', p_sale_id, 'customer', v_customer, 'total', v_sale.total,
        'pagado', v_sale.paid_amount, 'refund', v_refund_amount,
        'refunds', v_refund_entries, 'reason', NULLIF(btrim(p_reason), ''),
        'items', v_item_count,
        'itemIds', COALESCE((
          SELECT jsonb_agg(public.te_try_numeric(i.item ->> 'id')::bigint)
          FROM jsonb_array_elements(v_sale.items) i(item)
          WHERE public.te_try_numeric(i.item ->> 'id') IS NOT NULL
        ), '[]'::jsonb),
        'itemsDetail', v_sale.items,
        'dueDate', v_sale.due_date, 'request_id', p_request_id
      )
    );
  ELSE
    PERFORM public.te_log_activity(
      'venta_cancelada',
      format('Cancelo venta de $%s — %s producto(s)', v_sale.total, v_item_count),
      jsonb_build_object(
        'id', p_sale_id, 'total', v_sale.total, 'refund', v_refund_amount,
        'refunds', v_refund_entries, 'reason', NULLIF(btrim(p_reason), ''),
        'items', v_item_count,
        'itemIds', COALESCE((
          SELECT jsonb_agg(public.te_try_numeric(i.item ->> 'id')::bigint)
          FROM jsonb_array_elements(v_sale.items) i(item)
          WHERE public.te_try_numeric(i.item ->> 'id') IS NOT NULL
        ), '[]'::jsonb),
        'itemsDetail', v_sale.items,
        'request_id', p_request_id
      )
    );
  END IF;

  v_response := jsonb_build_object(
    'ok', true,
    'operation', v_operation,
    'request_id', p_request_id,
    'already_cancelled', false,
    'sale', jsonb_build_object(
      'id', p_sale_id,
      'origin_type', v_sale.origin_type,
      'type', 'venta',
      'status', 'cancelado',
      'cancelled_at', v_now,
      'refund_amount', v_refund_amount,
      'refunds', v_refund_entries,
      'version', v_sale.version + 1
    ),
    'products', public.te_products_state(v_product_ids)
  );

  PERFORM public.te_rpc_store(p_request_id, v_operation, p_sale_id, v_response);
  RETURN v_response;
END;
$$;

-- Devolucion total de un apartado SIN cancelarlo ni restaurar inventario.
-- Sirve para "Anular anticipo" de forma auditable y para reabrir un apartado
-- liquidado cuyo ultimo cobro fue un error.
CREATE OR REPLACE FUNCTION public.refund_apartado_atomic(
  p_request_id uuid,
  p_sale_id bigint,
  p_reason text,
  p_expected_version bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_operation      constant text := 'refund_apartado';
  v_cached         jsonb;
  v_response       jsonb;
  v_sale           public.sales%ROWTYPE;
  v_now            timestamptz := now();
  v_refunds        jsonb;
  v_refund_amount  numeric;
  v_product_ids    bigint[];
  v_customer       text;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'No autenticado';
  END IF;
  v_cached := public.te_rpc_replay(p_request_id, v_operation);
  IF v_cached IS NOT NULL THEN RETURN v_cached; END IF;
  IF NOT public.te_has_permission('canEditApartado') THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'Sin permiso para devolver pagos de apartados';
  END IF;
  PERFORM set_config('tresencantos.rpc_v2', 'on', true);
  PERFORM pg_advisory_xact_lock(hashtextextended('tresencantos:inventory', 0));

  SELECT * INTO v_sale
  FROM public.sales
  WHERE id = p_sale_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'Apartado no encontrado';
  END IF;
  IF p_expected_version IS NULL OR p_expected_version <> v_sale.version THEN
    RAISE EXCEPTION USING
      ERRCODE = '40001',
      MESSAGE = 'El apartado cambio en otro dispositivo; vuelve a cargarlo';
  END IF;
  IF v_sale.origin_type <> 'apartado' THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'El registro no es un apartado';
  END IF;
  IF v_sale.cancelled_at IS NOT NULL OR v_sale.status = 'cancelado' THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'El apartado esta cancelado';
  END IF;

  SELECT array_agg(d.product_id ORDER BY d.product_id)
    INTO v_product_ids
  FROM public.te_inventory_demand(v_sale.items) d;
  PERFORM p.id FROM public.products p
  WHERE p.id = ANY(v_product_ids)
  ORDER BY p.id
  FOR UPDATE;

  v_refunds := public.te_refund_sale_balance(
    p_sale_id, p_request_id, 'rpc_apartado_refund', p_reason, v_now
  );
  SELECT round(COALESCE(SUM(abs((e.entry ->> 'amount')::numeric)), 0), 2)
    INTO v_refund_amount
  FROM jsonb_array_elements(v_refunds) AS e(entry);
  IF v_refund_amount <= 0 THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'El apartado no tiene pagos por devolver';
  END IF;

  UPDATE public.sales
  SET
    paid_amount = 0,
    abonos = (CASE WHEN jsonb_typeof(abonos) = 'array' THEN abonos ELSE '[]'::jsonb END) || v_refunds,
    type = 'apartado',
    status = 'activo',
    liquidated_at = NULL,
    last_payment_at = v_now,
    updated_at = v_now,
    version = version + 1
  WHERE id = p_sale_id;

  PERFORM public.te_refresh_apartado_product_flags(v_product_ids);
  v_customer := COALESCE(split_part(v_sale.customer, ' · ', 1), 'cliente');
  PERFORM public.te_log_activity(
    'apartado_reembolso',
    format('Devolvio $%s del apartado de %s', v_refund_amount, v_customer),
    jsonb_build_object(
      'id', p_sale_id, 'customer', v_customer, 'refund', v_refund_amount,
      'refunds', v_refunds, 'reason', NULLIF(btrim(p_reason), ''),
      'items', CASE WHEN jsonb_typeof(v_sale.items) = 'array' THEN jsonb_array_length(v_sale.items) ELSE 0 END,
      'itemIds', COALESCE((
        SELECT jsonb_agg(public.te_require_positive_bigint(i.item ->> 'id', 'id de producto'))
        FROM jsonb_array_elements(
          CASE WHEN jsonb_typeof(v_sale.items) = 'array' THEN v_sale.items ELSE '[]'::jsonb END
        ) i(item)
      ), '[]'::jsonb),
      'itemsDetail', v_sale.items, 'request_id', p_request_id
    )
  );

  v_response := jsonb_build_object(
    'ok', true,
    'operation', v_operation,
    'request_id', p_request_id,
    'refunded', true,
    'refund_amount', v_refund_amount,
    'refunds', v_refunds,
    'sale', jsonb_build_object(
      'id', p_sale_id, 'origin_type', 'apartado', 'type', 'apartado',
      'status', 'activo', 'paid_amount', 0, 'remaining', v_sale.total,
      'liquidated_at', NULL, 'version', v_sale.version + 1
    ),
    'products', public.te_products_state(v_product_ids)
  );

  PERFORM public.te_rpc_store(p_request_id, v_operation, p_sale_id, v_response);
  RETURN v_response;
END;
$$;

-- -----------------------------------------------------------------------------
-- 9. Reconciliar flags despues de convertir apartados historicos pagados
-- -----------------------------------------------------------------------------

DO $$
DECLARE
  v_ids bigint[];
BEGIN
  SELECT array_agg(DISTINCT d.product_id ORDER BY d.product_id)
    INTO v_ids
  FROM public.sales s
  CROSS JOIN LATERAL public.te_inventory_demand(s.items) d
  WHERE s.origin_type = 'apartado';

  IF COALESCE(array_length(v_ids, 1), 0) > 0 THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('tresencantos:inventory', 0));
    PERFORM p.id FROM public.products p
    WHERE p.id = ANY(v_ids)
    ORDER BY p.id
    FOR UPDATE;
    PERFORM public.te_refresh_apartado_product_flags(v_ids);
  END IF;
END;
$$;

-- Solo JWT autenticado puede invocar RPCs publicos v2.
REVOKE ALL ON FUNCTION public.record_sale_atomic_v2(uuid, jsonb, numeric, numeric, text, text, boolean, numeric, text, date) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.record_apartado_payment_atomic(uuid, bigint, text, numeric, bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.edit_apartado_atomic(uuid, bigint, jsonb, bigint, numeric) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.cancel_sale_atomic(uuid, bigint, text, bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.refund_apartado_atomic(uuid, bigint, text, bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_pos_rpc_result(uuid) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.record_sale_atomic_v2(uuid, jsonb, numeric, numeric, text, text, boolean, numeric, text, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_apartado_payment_atomic(uuid, bigint, text, numeric, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.edit_apartado_atomic(uuid, bigint, jsonb, bigint, numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_sale_atomic(uuid, bigint, text, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.refund_apartado_atomic(uuid, bigint, text, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_pos_rpc_result(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_permissions() TO authenticated;

NOTIFY pgrst, 'reload schema';

COMMIT;

-- Verificacion sugerida (solo lectura):
-- SELECT origin_type, status, count(*) FROM public.sales GROUP BY 1,2 ORDER BY 1,2;
-- SELECT source, is_estimated, count(*), sum(amount) FROM public.sale_payments GROUP BY 1,2 ORDER BY 1,2;
-- SELECT count(*) AS paid_but_active
-- FROM public.sales
-- WHERE origin_type='apartado' AND status='activo' AND paid_amount >= total;
