-- =============================================================================
-- Clientes (MVP) -- tabla real de clientes vinculada a sales.customer_id.
--
-- Hoy sales.customer es texto libre ("Nombre · 📱 Tel"), sin FK -- cada venta
-- es una isla, no hay forma de ver el historial de una clienta ni detectar a
-- las recurrentes. Esta migracion:
--   1. Crea public.customers (identidad minima: nombre, telefono unico, notas).
--   2. Agrega sales.customer_id (FK nullable, aditiva).
--   3. Hace backfill de clientes/enlaces a partir del telefono ya guardado en
--      sales.customer (solo cuando hay 10 digitos -- sin telefono no se
--      inventa vinculo).
--   4. Extiende record_sale_atomic_v2 con p_customer_id (parametro opcional al
--      final, no rompe la llamada actual desde pos-checkout.js).
--   5. Agrega te_find_or_create_customer(p_name, p_phone) -- unico camino para
--      dar de alta un cliente (dedup por telefono), llamado desde Caja antes
--      de cobrar.
--
-- Ejecutar una sola vez en el SQL Editor de Supabase. Aditiva e idempotente
-- (CREATE TABLE/INDEX IF NOT EXISTS, backfill solo toca customer_id IS NULL).
-- =============================================================================
BEGIN;

-- -----------------------------------------------------------------------------
-- 1. Tabla customers
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  phone text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by_email text
);

-- Clave de deduplicacion: un telefono solo puede pertenecer a un cliente.
CREATE UNIQUE INDEX IF NOT EXISTS customers_phone_unique
  ON public.customers(phone) WHERE phone IS NOT NULL;

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'customers' AND policyname = 'customers_auth_select'
  ) THEN
    CREATE POLICY customers_auth_select ON public.customers
      FOR SELECT TO authenticated
      USING (auth.role() = 'authenticated');
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'customers' AND policyname = 'customers_auth_update'
  ) THEN
    -- Permite editar nombre/telefono/notas desde el perfil de Reportes,
    -- igual que products. El alta (INSERT) solo pasa por el RPC de abajo
    -- (SECURITY DEFINER, dueño de la tabla, bypasea RLS) para garantizar
    -- que todo alta respeta la deduplicacion por telefono.
    CREATE POLICY customers_auth_update ON public.customers
      FOR UPDATE TO authenticated
      USING (auth.role() = 'authenticated')
      WITH CHECK (auth.role() = 'authenticated');
  END IF;
END;
$$;

REVOKE ALL ON public.customers FROM PUBLIC, anon;
REVOKE INSERT, DELETE, TRUNCATE ON public.customers FROM authenticated;
GRANT SELECT, UPDATE ON public.customers TO authenticated;

-- -----------------------------------------------------------------------------
-- 2. sales.customer_id -- aditiva, nullable
-- -----------------------------------------------------------------------------
ALTER TABLE public.sales
  ADD COLUMN IF NOT EXISTS customer_id bigint REFERENCES public.customers(id) ON DELETE SET NULL;

-- -----------------------------------------------------------------------------
-- 3. Backfill -- crea clientes y enlaza ventas historicas que sí tienen
--    telefono en el texto libre (formato "Nombre · 📱 Tel", mismo separador
--    que usa el frontend en pos-checkout.js). Idempotente: solo toca filas
--    con customer_id IS NULL, nunca modifica sales.customer/total/created_at.
--
--    Dos statements separados (no un solo WITH ... INSERT ... UPDATE
--    encadenado): dentro de un mismo statement, un INSERT en un CTE no es
--    visible para otra parte de ese mismo statement salvo via su propio
--    RETURNING -- el UPDATE final necesita ver filas recien insertadas por
--    telefono, no solo las que el propio INSERT devolvió. Dos statements
--    en la misma transaccion sí ven los efectos confirmados uno del otro.
-- -----------------------------------------------------------------------------

-- 3a. Crear clientes nuevos a partir de telefonos historicos validos.
INSERT INTO public.customers (name, phone)
SELECT DISTINCT ON (phone) name, phone
FROM (
  SELECT
    s.id AS sale_id,
    btrim(split_part(s.customer, ' · 📱 ', 1)) AS name,
    NULLIF(regexp_replace(split_part(s.customer, ' · 📱 ', 2), '\D', '', 'g'), '') AS phone
  FROM public.sales s
  WHERE s.customer IS NOT NULL
    AND s.customer_id IS NULL
    AND s.customer LIKE '%· 📱 %'
) extracted
WHERE phone IS NOT NULL AND length(phone) = 10 AND name <> ''
ORDER BY phone, sale_id DESC -- nombre de la venta mas reciente por telefono
ON CONFLICT (phone) WHERE phone IS NOT NULL DO NOTHING;

-- 3b. Enlazar sales.customer_id contra los clientes ya existentes/recien creados.
UPDATE public.sales s
SET customer_id = c.id
FROM (
  SELECT
    s2.id AS sale_id,
    NULLIF(regexp_replace(split_part(s2.customer, ' · 📱 ', 2), '\D', '', 'g'), '') AS phone
  FROM public.sales s2
  WHERE s2.customer IS NOT NULL
    AND s2.customer_id IS NULL
    AND s2.customer LIKE '%· 📱 %'
) v
JOIN public.customers c ON c.phone = v.phone
WHERE s.id = v.sale_id AND v.phone IS NOT NULL AND length(v.phone) = 10;

-- -----------------------------------------------------------------------------
-- 4. record_sale_atomic_v2 -- agrega p_customer_id al final (aditivo,
--    DEFAULT NULL). PostgREST llama por nombre de parametro: la llamada
--    actual desde pos-checkout.js sigue funcionando igual si no manda este
--    parametro. Cuerpo identico al vigente (20260821_01_override_pin.sql)
--    salvo la columna/valor customer_id en el INSERT.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.record_sale_atomic_v2(
  p_request_id uuid,
  p_items jsonb,
  p_total numeric,
  p_discount numeric DEFAULT 0,
  p_payment_method text DEFAULT 'efectivo',
  p_note text DEFAULT NULL,
  p_is_apartado boolean DEFAULT false,
  p_paid_amount numeric DEFAULT NULL,
  p_customer text DEFAULT NULL,
  p_due_date date DEFAULT NULL,
  p_override_tickets uuid[] DEFAULT NULL,
  p_customer_id bigint DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_operation      constant text := 'record_sale_v2';
  v_cached         jsonb;
  v_response       jsonb;
  v_items          jsonb;
  v_sale_id        bigint;
  v_parent_ids     bigint[];
  v_product_ids    bigint[];
  v_subtotal       numeric;
  v_discount       numeric;
  v_total          numeric;
  v_paid           numeric;
  v_tendered       numeric;
  v_origin         text;
  v_status         text;
  v_type           text;
  v_now            timestamptz := now();
  v_abonos         jsonb;
  v_customer       text := NULLIF(btrim(p_customer), '');
  v_actor_email    text := lower(auth.jwt() ->> 'email');
  v_short_customer text;
  v_shortage       record;
  v_price_overridden boolean;
  v_authorized_by  text;
  v_authorized_price_by text;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'No autenticado';
  END IF;

  v_cached := public.te_rpc_replay(p_request_id, v_operation);
  IF v_cached IS NOT NULL THEN RETURN v_cached; END IF;

  PERFORM set_config('tresencantos.rpc_v2', 'on', true);

  -- Todos los RPC de inventario toman el mismo advisory lock antes de filas.
  PERFORM pg_advisory_xact_lock(hashtextextended('tresencantos:inventory', 0));

  IF jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'La venta debe tener productos';
  END IF;
  IF lower(COALESCE(p_payment_method, '')) NOT IN ('efectivo', 'transferencia') THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Metodo de pago invalido';
  END IF;
  IF p_is_apartado AND v_customer IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'El cliente es obligatorio para un apartado';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM (
      SELECT public.te_try_numeric(x.item ->> 'id') AS raw_id
      FROM jsonb_array_elements(p_items) AS x(item)
    ) q
    WHERE raw_id IS NULL OR raw_id <= 0 OR raw_id <> trunc(raw_id)
       OR raw_id > 9223372036854775807::numeric
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Hay productos con id invalido';
  END IF;

  SELECT array_agg(DISTINCT q.raw_id::bigint ORDER BY q.raw_id::bigint)
    INTO v_parent_ids
  FROM (
    SELECT public.te_try_numeric(x.item ->> 'id') AS raw_id
    FROM jsonb_array_elements(p_items) AS x(item)
  ) q;

  PERFORM p.id FROM public.products p
  WHERE p.id = ANY(v_parent_ids)
  ORDER BY p.id
  FOR UPDATE;

  IF (SELECT COUNT(*) FROM public.products p WHERE p.id = ANY(v_parent_ids))
     <> COALESCE(array_length(v_parent_ids, 1), 0) THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'Uno o mas productos ya no existen';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.products p
    WHERE p.id = ANY(v_parent_ids) AND COALESCE(p.is_archived, false)
  ) THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = 'Un producto fue archivado; recarga la caja antes de cobrar';
  END IF;

  v_items := public.te_snapshot_sale_items(p_items, p_override_tickets);
  v_price_overridden := EXISTS (
    SELECT 1 FROM jsonb_array_elements(v_items) e WHERE e.value ? 'original_price'
  );
  IF v_price_overridden AND NOT public.te_has_permission('canOverridePrice') THEN
    v_authorized_price_by := public.te_consume_matching_override('canOverridePrice', p_override_tickets);
    IF v_authorized_price_by IS NULL THEN
      RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'Autorización de precio inválida o expirada';
    END IF;
  END IF;

  SELECT COALESCE(SUM((x.item ->> 'subtotal')::numeric), 0)
    INTO v_subtotal
  FROM jsonb_array_elements(v_items) AS x(item);

  v_discount := round(COALESCE(p_discount, 0), 2);
  IF NOT public.te_numeric_is_finite(v_discount)
     OR v_discount < 0 OR v_discount > v_subtotal THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Descuento invalido';
  END IF;
  IF v_discount > 0 AND NOT public.te_permission_or_override('canApplyDiscount', p_override_tickets) THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'Sin permiso para aplicar descuentos';
  END IF;
  IF v_discount > 0 AND NOT public.te_has_permission('canApplyDiscount') THEN
    v_authorized_by := public.te_consume_matching_override('canApplyDiscount', p_override_tickets);
    IF v_authorized_by IS NULL THEN
      RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'Autorización de descuento inválida o expirada';
    END IF;
  END IF;
  v_authorized_by := COALESCE(v_authorized_by, v_authorized_price_by);
  v_total := round(v_subtotal - v_discount, 2);
  IF v_total <= 0 THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'El total debe ser mayor a cero';
  END IF;
  IF NOT public.te_numeric_is_finite(p_total)
     OR abs(round(p_total, 2) - v_total) >= 0.005 THEN
    RAISE EXCEPTION USING
      ERRCODE = '22023',
      MESSAGE = format('El total cambio: esperado %s, recibido %s', v_total, COALESCE(p_total, 0));
  END IF;

  IF p_is_apartado THEN
    v_paid := round(COALESCE(p_paid_amount, 0), 2);
    IF NOT public.te_numeric_is_finite(v_paid)
       OR v_paid < 0 OR v_paid > v_total THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'El anticipo no puede superar el total';
    END IF;
    v_tendered := v_paid;
    v_origin := 'apartado';
    IF v_paid >= v_total THEN
      v_status := 'liquidado'; v_type := 'venta';
    ELSE
      v_status := 'activo'; v_type := 'apartado';
    END IF;
  ELSE
    v_paid := v_total;
    v_tendered := round(COALESCE(p_paid_amount, v_total), 2);
    IF NOT public.te_numeric_is_finite(v_tendered) OR v_tendered < v_total THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'El pago no cubre el total';
    END IF;
    v_origin := 'venta'; v_status := 'liquidado'; v_type := 'venta';
  END IF;

  SELECT array_agg(d.product_id ORDER BY d.product_id)
    INTO v_product_ids
  FROM public.te_inventory_demand(v_items) d;

  PERFORM p.id FROM public.products p
  WHERE p.id = ANY(v_product_ids)
  ORDER BY p.id
  FOR UPDATE;

  IF (SELECT COUNT(*) FROM public.products p WHERE p.id = ANY(v_product_ids))
     <> COALESCE(array_length(v_product_ids, 1), 0) THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'Un componente del kit ya no existe';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.products p
    WHERE p.id = ANY(v_product_ids) AND COALESCE(p.is_archived, false)
  ) THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = 'Un producto o componente fue archivado; recarga la caja antes de cobrar';
  END IF;

  SELECT d.product_id, d.required_qty, COALESCE(p.stock, 0) AS stock
    INTO v_shortage
  FROM public.te_inventory_demand(v_items) d
  JOIN public.products p ON p.id = d.product_id
  WHERE COALESCE(p.stock, 0) < d.required_qty
  ORDER BY d.product_id
  LIMIT 1;
  IF FOUND THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = format('Sin stock suficiente para producto id=%s (disponible %s, requerido %s)',
                       v_shortage.product_id, v_shortage.stock, v_shortage.required_qty);
  END IF;

  v_abonos := CASE
    WHEN p_is_apartado AND v_paid > 0 THEN jsonb_build_array(jsonb_build_object(
      'amount', v_paid,
      'method', lower(p_payment_method),
      'date', v_now,
      'request_id', p_request_id,
      'collected_by', v_actor_email,
      'kind', 'payment'
    ))
    ELSE NULL
  END;

  INSERT INTO public.sales (
    total, items, discount, payment_method, note, type, paid_amount,
    customer, customer_id, due_date, seller_email, abonos,
    origin_type, status, liquidated_at, last_payment_at, updated_at, version
  ) VALUES (
    v_total,
    v_items,
    NULLIF(v_discount, 0),
    lower(p_payment_method),
    NULLIF(btrim(p_note), ''),
    v_type,
    v_tendered,
    v_customer,
    p_customer_id,
    CASE WHEN p_is_apartado THEN p_due_date ELSE NULL END,
    v_actor_email,
    v_abonos,
    v_origin,
    v_status,
    CASE WHEN v_status = 'liquidado' THEN v_now ELSE NULL END,
    CASE WHEN (NOT p_is_apartado) OR v_paid > 0 THEN v_now ELSE NULL END,
    v_now,
    0
  )
  RETURNING id INTO v_sale_id;

  INSERT INTO public.sale_payments (
    sale_id, request_id, kind, amount, method, paid_at,
    collected_by, collected_by_email, is_estimated, source, meta
  )
  SELECT
    v_sale_id,
    p_request_id,
    'payment',
    CASE WHEN p_is_apartado THEN v_paid ELSE v_total END,
    lower(p_payment_method),
    v_now,
    auth.uid(),
    v_actor_email,
    false,
    CASE WHEN p_is_apartado THEN 'rpc_apartado_initial' ELSE 'rpc_direct_sale' END,
    jsonb_build_object('origin_type', v_origin)
  WHERE (NOT p_is_apartado) OR v_paid > 0;

  WITH demand AS (
    SELECT * FROM public.te_inventory_demand(v_items)
  )
  UPDATE public.products p
  SET stock = COALESCE(p.stock, 0) - d.required_qty
  FROM demand d
  WHERE p.id = d.product_id;

  PERFORM public.te_refresh_apartado_product_flags(v_product_ids);

  v_short_customer := COALESCE(split_part(v_customer, ' · ', 1), 'cliente');
  IF p_is_apartado AND v_status = 'activo' THEN
    PERFORM public.te_log_activity(
      'apartado_nuevo',
      format('Apartado de %s — $%s%s', v_short_customer, v_total,
             CASE WHEN v_price_overridden THEN ' (precio modificado)' ELSE '' END),
      jsonb_build_object(
        'id', v_sale_id, 'customer', v_short_customer, 'total', v_total,
        'anticipo', v_paid, 'pendiente', v_total - v_paid,
        'dueDate', p_due_date, 'items', jsonb_array_length(v_items),
        'itemIds', to_jsonb(v_parent_ids), 'itemsDetail', v_items,
        'price_overridden', v_price_overridden, 'authorized_by', v_authorized_by,
        'request_id', p_request_id
      )
    );
  ELSIF p_is_apartado THEN
    PERFORM public.te_log_activity(
      'apartado_liquidado',
      format('Apartado pagado completo de %s — $%s%s', v_short_customer, v_total,
             CASE WHEN v_price_overridden THEN ' (precio modificado)' ELSE '' END),
      jsonb_build_object(
        'id', v_sale_id, 'customer', v_short_customer, 'total', v_total,
        'method', lower(p_payment_method), 'items', jsonb_array_length(v_items),
        'itemIds', to_jsonb(v_parent_ids), 'itemsDetail', v_items,
        'price_overridden', v_price_overridden, 'authorized_by', v_authorized_by,
        'request_id', p_request_id
      )
    );
  ELSE
    PERFORM public.te_log_activity(
      'venta',
      format('Cobro $%s — %s producto(s)%s', v_total, jsonb_array_length(v_items),
             CASE WHEN v_price_overridden THEN ' (precio modificado)' ELSE '' END),
      jsonb_build_object(
        'id', v_sale_id, 'total', v_total, 'method', lower(p_payment_method),
        'discount', v_discount, 'items', jsonb_array_length(v_items),
        'itemIds', to_jsonb(v_parent_ids), 'itemsDetail', v_items,
        'price_overridden', v_price_overridden, 'authorized_by', v_authorized_by,
        'request_id', p_request_id
      )
    );
  END IF;

  v_response := jsonb_build_object(
    'ok', true,
    'operation', v_operation,
    'request_id', p_request_id,
    'liquidated', (v_status = 'liquidado'),
    'sale', jsonb_build_object(
      'id', v_sale_id,
      'origin_type', v_origin,
      'status', v_status,
      'type', v_type,
      'total', v_total,
      'paid_amount', CASE WHEN p_is_apartado THEN v_paid ELSE v_tendered END,
      'remaining', CASE WHEN p_is_apartado THEN v_total - v_paid ELSE 0 END,
      'liquidated_at', CASE WHEN v_status = 'liquidado' THEN v_now ELSE NULL END,
      'version', 0
    ),
    'products', public.te_products_state(v_product_ids)
  );

  PERFORM public.te_rpc_store(p_request_id, v_operation, v_sale_id, v_response);
  RETURN v_response;
END;
$$;

-- -----------------------------------------------------------------------------
-- 5. te_find_or_create_customer -- unico camino para dar de alta un cliente.
--    Sin permiso especial (dar de alta un cliente es tan de bajo riesgo como
--    agregar un producto, ya libre para todos los roles). Deduplica por
--    telefono via el indice unico parcial; sin telefono siempre crea (no hay
--    con que deduplicar). No usa p_request_id/te_rpc_replay: es naturalmente
--    idempotente (reintentar encuentra el mismo registro por telefono), no
--    mueve dinero ni stock.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.te_find_or_create_customer(
  p_name text,
  p_phone text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_name    text := NULLIF(btrim(p_name), '');
  v_phone   text := NULLIF(regexp_replace(COALESCE(p_phone, ''), '\D', '', 'g'), '');
  v_id      bigint;
  v_created boolean := false;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'No autenticado';
  END IF;
  IF v_name IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Nombre requerido';
  END IF;
  IF v_phone IS NOT NULL AND length(v_phone) <> 10 THEN
    v_phone := NULL; -- telefono incompleto/invalido: se ignora, no bloquea
  END IF;

  IF v_phone IS NOT NULL THEN
    SELECT id INTO v_id FROM public.customers WHERE phone = v_phone;
  END IF;

  IF v_id IS NULL THEN
    INSERT INTO public.customers (name, phone, created_by_email)
    VALUES (v_name, v_phone, lower(auth.jwt() ->> 'email'))
    ON CONFLICT (phone) WHERE phone IS NOT NULL DO NOTHING
    RETURNING id INTO v_id;

    IF v_id IS NULL AND v_phone IS NOT NULL THEN
      -- Otra caja lo creo en el mismo instante (condicion de carrera) --
      -- resolver contra el registro que sí quedo.
      SELECT id INTO v_id FROM public.customers WHERE phone = v_phone;
    END IF;
    v_created := (v_id IS NOT NULL);
  END IF;

  IF v_created THEN
    PERFORM public.te_log_activity(
      'cliente_creado',
      format('Nuevo cliente: %s', v_name),
      jsonb_build_object('id', v_id, 'name', v_name, 'phone', v_phone)
    );
  END IF;

  RETURN jsonb_build_object('id', v_id, 'name', v_name, 'created', v_created);
END;
$$;

REVOKE ALL ON FUNCTION public.te_find_or_create_customer(text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.te_find_or_create_customer(text, text) TO authenticated;

COMMIT;
