-- =============================================================================
-- Turnos de caja: apertura/cierre real, con hora, fondo, conteo y diferencia.
--
-- Antes de esta migración, "el turno" solo existía en localStorage del
-- dispositivo (_posEnsureCurrentShift en pos-core.js) -- se creaba en
-- silencio la primera vez que alguien abría Caja ese día, sin pedir nada y
-- sin llegar nunca a Supabase. Ofelia no tenía forma de saber a qué hora
-- Areli/quien sea realmente abrió o cerró caja, ni si contó el efectivo.
--
-- Esta migración agrega una tabla real + 2 RPC transaccionales:
--   - te_open_cash_shift(p_fondo_inicial)   -- abrir caja (obligatorio en la UI
--     antes de poder vender, ver _posShiftGateInit() en pos-core.js)
--   - te_close_cash_shift(p_conteo_final, p_gastos_total) -- cerrar caja: calcula
--     efectivo neto y esperado del lado del servidor (no confía en el cliente),
--     guarda la diferencia y vuelve a exigir abrir un turno nuevo para seguir
--     vendiendo.
-- Ambas quedan auditadas en activity_log (turno_abierto/turno_cerrado/
-- turno_cerrado_auto) y visibles en Reportes ("Turnos de caja").
--
-- Ejecutar una sola vez en el SQL Editor de Supabase. Aditiva e idempotente
-- (CREATE TABLE/INDEX IF NOT EXISTS, CREATE OR REPLACE FUNCTION).
-- =============================================================================
BEGIN;

-- -----------------------------------------------------------------------------
-- 1. Tabla cash_shifts
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cash_shifts (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email     text NOT NULL,
  opened_at      timestamptz NOT NULL DEFAULT now(),
  closed_at      timestamptz,
  fondo_inicial  numeric NOT NULL DEFAULT 0,
  conteo_final   numeric,
  efectivo_neto  numeric,
  gastos_total   numeric,
  esperado       numeric,
  diferencia     numeric,
  status         text NOT NULL DEFAULT 'abierto'
                 CHECK (status IN ('abierto', 'cerrado', 'cerrado_auto')),
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS cash_shifts_user_status_idx ON public.cash_shifts(user_email, status);
CREATE INDEX IF NOT EXISTS cash_shifts_opened_at_idx ON public.cash_shifts(opened_at DESC);

ALTER TABLE public.cash_shifts ENABLE ROW LEVEL SECURITY;

-- Lectura amplia para cualquier autenticado -- mismo criterio que
-- sales_auth_select: la restricción real de quién ve qué vive en la UI
-- (get_my_permissions/canViewReports) y en que solo las RPC de abajo pueden
-- escribir. El personal de Caja de esta tienda es de confianza (2-4 cuentas).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'cash_shifts' AND policyname = 'cash_shifts_select_auth'
  ) THEN
    CREATE POLICY cash_shifts_select_auth ON public.cash_shifts
      FOR SELECT TO authenticated
      USING (true);
  END IF;
END $$;

-- Sin políticas de INSERT/UPDATE/DELETE: toda escritura pasa por las RPC
-- SECURITY DEFINER de abajo (mismo patrón que sales tras el lockdown de Caja v2).
REVOKE ALL ON public.cash_shifts FROM anon;
GRANT SELECT ON public.cash_shifts TO authenticated;

-- -----------------------------------------------------------------------------
-- 2. te_open_cash_shift -- abre un turno nuevo para el usuario autenticado.
--    Si ya tenía uno abierto (se le olvidó cerrar, se quedó sin batería, etc.)
--    lo cierra automáticamente sin conteo (status 'cerrado_auto') en vez de
--    bloquear la apertura de uno nuevo -- deja rastro de que no se cerró a
--    mano, pero nunca deja a alguien sin poder trabajar.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.te_open_cash_shift(p_fondo_inicial numeric)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_email text;
  v_open  public.cash_shifts;
  v_new   public.cash_shifts;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'No autenticado';
  END IF;
  v_email := lower(coalesce(auth.jwt()->>'email', ''));
  IF v_email = '' THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'No se pudo identificar el usuario';
  END IF;
  IF p_fondo_inicial IS NULL OR p_fondo_inicial < 0 THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Fondo inicial inválido';
  END IF;

  SELECT * INTO v_open FROM public.cash_shifts
   WHERE user_email = v_email AND status = 'abierto'
   ORDER BY opened_at DESC LIMIT 1
   FOR UPDATE;

  IF FOUND THEN
    UPDATE public.cash_shifts
       SET status = 'cerrado_auto', closed_at = now()
     WHERE id = v_open.id;

    INSERT INTO public.activity_log(action, user_email, summary, meta)
    VALUES ('turno_cerrado_auto', v_email,
            'Turno anterior cerrado automáticamente (sin conteo) al abrir uno nuevo',
            jsonb_build_object('shift_id', v_open.id, 'opened_at', v_open.opened_at));
  END IF;

  INSERT INTO public.cash_shifts(user_email, fondo_inicial, status)
  VALUES (v_email, p_fondo_inicial, 'abierto')
  RETURNING * INTO v_new;

  INSERT INTO public.activity_log(action, user_email, summary, meta)
  VALUES ('turno_abierto', v_email,
          format('Abrió caja con fondo de $%s', trim(to_char(p_fondo_inicial, 'FM999,999,990.00'))),
          jsonb_build_object('shift_id', v_new.id, 'fondo_inicial', p_fondo_inicial));

  RETURN to_jsonb(v_new);
END;
$$;

REVOKE ALL ON FUNCTION public.te_open_cash_shift(numeric) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.te_open_cash_shift(numeric) TO authenticated;

-- -----------------------------------------------------------------------------
-- 3. te_close_cash_shift -- cierra el turno abierto del usuario. Calcula
--    efectivo_neto/esperado en el servidor a partir de sale_payments (no
--    confía en el total que traiga el cliente) -- solo gastos_total viene del
--    cliente porque los gastos del turno hoy solo existen en localStorage
--    (fuera de alcance de esta migración; ver Deudas Técnicas en CLAUDE.md).
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.te_close_cash_shift(p_conteo_final numeric, p_gastos_total numeric DEFAULT 0)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_email     text;
  v_shift     public.cash_shifts;
  v_efectivo  numeric;
  v_esperado  numeric;
  v_diff      numeric;
  v_gastos    numeric := coalesce(p_gastos_total, 0);
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'No autenticado';
  END IF;
  v_email := lower(coalesce(auth.jwt()->>'email', ''));

  SELECT * INTO v_shift FROM public.cash_shifts
   WHERE user_email = v_email AND status = 'abierto'
   ORDER BY opened_at DESC LIMIT 1
   FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = 'P0002', MESSAGE = 'No tienes un turno abierto';
  END IF;
  IF p_conteo_final IS NULL OR p_conteo_final < 0 THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Conteo final inválido';
  END IF;

  SELECT coalesce(sum(sp.amount), 0) INTO v_efectivo
    FROM public.sale_payments sp
    JOIN public.sales s ON s.id = sp.sale_id
   WHERE lower(sp.collected_by_email) = v_email
     AND sp.method = 'efectivo'
     AND sp.paid_at >= v_shift.opened_at
     AND sp.paid_at <= now()
     AND coalesce(s.is_test, false) = false;

  v_esperado := v_shift.fondo_inicial + v_efectivo - v_gastos;
  v_diff := p_conteo_final - v_esperado;

  UPDATE public.cash_shifts
     SET status = 'cerrado',
         closed_at = now(),
         conteo_final = p_conteo_final,
         efectivo_neto = v_efectivo,
         gastos_total = v_gastos,
         esperado = v_esperado,
         diferencia = v_diff
   WHERE id = v_shift.id
   RETURNING * INTO v_shift;

  INSERT INTO public.activity_log(action, user_email, summary, meta)
  VALUES ('turno_cerrado', v_email,
          format('Cerró caja -- esperado $%s, contado $%s (%s$%s)',
                 trim(to_char(v_esperado, 'FM999,999,990.00')),
                 trim(to_char(p_conteo_final, 'FM999,999,990.00')),
                 CASE WHEN v_diff >= 0 THEN '+' ELSE '-' END,
                 trim(to_char(abs(v_diff), 'FM999,999,990.00'))),
          jsonb_build_object('shift_id', v_shift.id, 'fondo_inicial', v_shift.fondo_inicial,
                              'efectivo_neto', v_efectivo, 'gastos_total', v_gastos,
                              'esperado', v_esperado, 'conteo_final', p_conteo_final,
                              'diferencia', v_diff));

  RETURN to_jsonb(v_shift);
END;
$$;

REVOKE ALL ON FUNCTION public.te_close_cash_shift(numeric, numeric) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.te_close_cash_shift(numeric, numeric) TO authenticated;

COMMIT;
