-- =============================================================================
-- Checador simple: registro real de entrada/salida, separado del control de
-- caja (cash_shifts).
--
-- Eduardo pidió saber a qué hora entra/sale cada quien de la tienda. "Cerrar
-- caja" no sirve para eso: alguien puede cerrar su turno y quedarse
-- trabajando (acomodando mercancía, limpiando), o salir sin haber cerrado
-- caja -- son dos preguntas de negocio distintas ("¿cuadra el dinero?" vs.
-- "¿a qué hora estuvo aquí cada quien?"). Los horarios varían demasiado
-- persona/día (Areli 11-5 entre semana, a veces 11-2, fines de semana 11-5;
-- Eduardo a veces 9:30-1:30) para modelar un horario fijo -- este checador
-- no valida horario, solo registra la hora real de entrada y salida.
--
-- Misma mecánica que cash_shifts: tabla + 2 RPC SECURITY DEFINER, auditado
-- en activity_log (checador_entrada/checador_salida/checador_salida_olvidada).
-- Sin fondo, sin conteo, sin diferencia -- no hay dinero que reconciliar aquí.
--
-- Ejecutar una sola vez en el SQL Editor de Supabase. Aditiva e idempotente.
-- =============================================================================
BEGIN;

CREATE TABLE IF NOT EXISTS public.attendance_shifts (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email  text NOT NULL,
  entrada_at  timestamptz NOT NULL DEFAULT now(),
  salida_at   timestamptz,
  status      text NOT NULL DEFAULT 'abierto'
              CHECK (status IN ('abierto', 'cerrado', 'cerrado_auto')),
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS attendance_shifts_user_status_idx ON public.attendance_shifts(user_email, status);
CREATE INDEX IF NOT EXISTS attendance_shifts_entrada_at_idx ON public.attendance_shifts(entrada_at DESC);

ALTER TABLE public.attendance_shifts ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'attendance_shifts' AND policyname = 'attendance_shifts_select_auth'
  ) THEN
    CREATE POLICY attendance_shifts_select_auth ON public.attendance_shifts
      FOR SELECT TO authenticated
      USING (true);
  END IF;
END $$;

REVOKE ALL ON public.attendance_shifts FROM anon;
GRANT SELECT ON public.attendance_shifts TO authenticated;

-- -----------------------------------------------------------------------------
-- te_clock_in() -- registra la entrada del usuario autenticado. Si ya tenía
-- una entrada abierta (se le olvidó marcar salida el día anterior), la
-- cierra sola sin hora de salida (status 'cerrado_auto', salida_at queda
-- NULL porque de verdad no se sabe a qué hora se fue) y lo deja en
-- Actividad como señal de que faltó marcar salida.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.te_clock_in()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_email text;
  v_open  public.attendance_shifts;
  v_new   public.attendance_shifts;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'No autenticado';
  END IF;
  v_email := lower(coalesce(auth.jwt()->>'email', ''));
  IF v_email = '' THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'No se pudo identificar el usuario';
  END IF;

  SELECT * INTO v_open FROM public.attendance_shifts
   WHERE user_email = v_email AND status = 'abierto'
   ORDER BY entrada_at DESC LIMIT 1
   FOR UPDATE;

  IF FOUND THEN
    UPDATE public.attendance_shifts
       SET status = 'cerrado_auto'
     WHERE id = v_open.id;

    INSERT INTO public.activity_log(action, user_email, summary, meta)
    VALUES ('checador_salida_olvidada', v_email,
            'No registró su salida antes de la siguiente entrada',
            jsonb_build_object('attendance_id', v_open.id, 'entrada_at', v_open.entrada_at));
  END IF;

  INSERT INTO public.attendance_shifts(user_email, status)
  VALUES (v_email, 'abierto')
  RETURNING * INTO v_new;

  INSERT INTO public.activity_log(action, user_email, summary, meta)
  VALUES ('checador_entrada', v_email, 'Registró su entrada',
          jsonb_build_object('attendance_id', v_new.id));

  RETURN to_jsonb(v_new);
END;
$$;

REVOKE ALL ON FUNCTION public.te_clock_in() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.te_clock_in() TO authenticated;

-- -----------------------------------------------------------------------------
-- te_clock_out() -- registra la salida del usuario autenticado sobre su
-- entrada abierta. Sin entrada abierta, error (nada que cerrar).
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.te_clock_out()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_email text;
  v_shift public.attendance_shifts;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'No autenticado';
  END IF;
  v_email := lower(coalesce(auth.jwt()->>'email', ''));

  SELECT * INTO v_shift FROM public.attendance_shifts
   WHERE user_email = v_email AND status = 'abierto'
   ORDER BY entrada_at DESC LIMIT 1
   FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = 'P0002', MESSAGE = 'No tienes una entrada registrada';
  END IF;

  UPDATE public.attendance_shifts
     SET status = 'cerrado', salida_at = now()
   WHERE id = v_shift.id
   RETURNING * INTO v_shift;

  INSERT INTO public.activity_log(action, user_email, summary, meta)
  VALUES ('checador_salida', v_email, 'Registró su salida',
          jsonb_build_object('attendance_id', v_shift.id, 'entrada_at', v_shift.entrada_at,
                              'salida_at', v_shift.salida_at));

  RETURN to_jsonb(v_shift);
END;
$$;

REVOKE ALL ON FUNCTION public.te_clock_out() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.te_clock_out() TO authenticated;

COMMIT;
